### ISSUE TITLE
Ability to edit URL slug

### ISSUE THREAD

**Issue by alan-null** [WeTeam/WeBlog#100]
At the moment this can be done only in _Content Editor_ via _rename_ operation.
The idea is to provide ability to change the url slug of the current blog post in _Page Editor/Experience Editor_

**Comment by adeneys** [comment]
Although this is a nice suggestion, I think it would confuse content authors if we implemented it. Sitecore ties the entry name to the URL, the same as it does for all items in the content tree. And this is what Sitecore users will expect. If we added something specific to WeBlog it would then make WeBlog items behave differently to all others.

At this stage I don't think we should pursue this feature.
