### ISSUE TITLE
Markdown for Sitecore Support (Plugin?)

### ISSUE THREAD

**Issue by techphoria414** [WeTeam/WeBlog#103]
Allow posts to (optionally?) use [Markdown for Sitecore](http://getfishtank.ca/blog/module-markdown-for-sitecore).

Would likely need to be separate fields for Markdown content, could do some tricks with the getContentEditorFields pipeline to hide the existing Rich Text fields. Or, could be a different template entirely?

**Comment by adeneys** [comment]
I think the use of Markdown is likely something authors would want across all their content, and not just limited to blog entries. Therefore I think this is probably best handled across the site and not made specific to WeBlog.
