### ISSUE TITLE
Sites Running WeBlog

### ISSUE THREAD

**Issue by uwe-e** [WeTeam/WeBlog#113]
Hi there,

we've been running several blogs.

http://www.swissbau.ch/de-CH/news/blog.aspx
http://www.muba.ch/de-CH/FuerMedien/FuerIhreBerichterstattung/Medienmitteilungen.aspx
http://www.mch-group.com/de-CH/News/Medienmitteilungen.aspx

best regards
Uwe

**Comment by alan-null** [comment]
Hi @uwe-e,

Thank you for sharing. I will update our wiki page.

Best Regards,
Alan
