### ISSUE TITLE
Captcha throws error during postback

### ISSUE THREAD

**Issue by alan-null** [WeTeam/WeBlog#115]
**How to reproduce:**
1. Go to some post
2. Add comment
3. When page will refresh hit F5

**Actual:**
You will see YSOD
![image](https://cloud.githubusercontent.com/assets/6848691/10709876/6bb656a6-7a3e-11e5-9692-09ec591f5fd4.png)

**Expected:**
No errors, fail silently.

**Comment by allanChacon** [comment]
I'm still getting this error in the package for Sitecore 7.5

**Comment by alan-null** [comment]
Hello @allanChacon,

Notice the date of latest [release](https://github.com/WeTeam/WeBlog/releases) is 15 Sep 2015

And the commit date 
`alan-null added a commit to alan-null/WeBlog that referenced this issue on 24 Oct 2015`

which means that all fixes merged after **15 Sep 2015** are not released yet.

Regarding bug fix.
Use of `try` and `catch` to catch specific exceptions is a standard approach when you are dealing with code that you cannot change (in this case error occured in Captcha module).


You've got two options:
* wait until we release the next version (I am not sure when it will happen, we need to deal with these [issues](https://github.com/WeTeam/WeBlog/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22release+3.0%22)) 
* fix it by yourself
 * download master branch, 
 * apply fix
 * build project
 * change DLL in your Website
