### ISSUE TITLE
Reorganize solution

### ISSUE THREAD

**Issue by alan-null** [WeTeam/WeBlog#119]
Currently there are two projects:
* Sitecore.Modules.WeBlog
* Test

Split it into:
* Sitecore.Modules.WeBlog
* Sitecore.Modules.WeBlog.WebForms
* Sitecore.Modules.WeBlog.Mvc
* Test.

**Comment by adeneys** [comment]
Note, the test project has been split out to "Unit Tests" and "Integration Tests".
