### ISSUE TITLE
Multiple template support

### ISSUE THREAD

**Issue by adeneys** [WeTeam/WeBlog#12]
Migrated from Trac. Trac ID 42

Current manager classes search based on the template IDs defined in config and don't check for derived templates. This needs to be updated to allow using multiple different templates on a single site.

**Comment by vikrantpunwatkar** [comment]
Hi,

I have worked on an alternative as suggested by @alan-null and created a package consisting of custom templates and config patch.

https://drive.google.com/folderview?id=0B16y8lyOflLYUjZTNjFkMFNJcFk&usp=sharing

I didn't get time for thorough testing but I have checked basic functionality and it works as expected.

Though this fulfills my need, this solution has one big drawback. You are able to use only one set of templates per Sitecore instance.

I hope this helps at least few of you.

**Comment by adeneys** [comment]
I believe this to be working and was required to support our MVC features. Retest before release.
