### ISSUE TITLE
Components thumbnails

### ISSUE THREAD

**Issue by alan-null** [WeTeam/WeBlog#120]
Currently MVC and WebForms uses the same thumbnails, which may be little bit confusing for administrators
![image](https://cloud.githubusercontent.com/assets/6848691/10889950/44dcda92-8195-11e5-8d0a-9efeb02e88cb.png)

Different thumbnails, different naming or special solution for dynamic available components? We should discuss that.

**Comment by adeneys** [comment]
Perhaps we just add the view engine onto the end of the component: "Archive - MVC", "Archive - WebForms". See if we can do that through the display name so code won't be affected if implementers change the title.

We should also take new screenshots once the new default theme is implemented.
