### ISSUE TITLE
Fix sc.variables in config

### ISSUE THREAD

**Issue by adeneys** [WeTeam/WeBlog#13]
Migrated from Trac. Trac ID 56

The Captcha text doesn't get translated|The text "Please confirm you are human by typing the text you see in this image:" doesn't get translated when you swithc to another languages.

In Japanese it should be 上の画像に表示されている文字をフォームに入力してください:

**Comment by alan-null** [comment]
This will be resolved in different way. See @https://github.com/WeTeam/WeBlog/issues/143
