### ISSUE TITLE
Index configuration for Sitecore 7.2

### ISSUE THREAD

**Issue by adeneys** [WeTeam/WeBlog#140]
The index configuration for Sitecore 7.2 is not correct and does not work.

**Comment by alan-null** [comment]
I was so excited with bug report so I didn't notice that you was already assigned.
I did a quick research and it seems that we will have to create separate ContentSearch config for SC72.

I did following changes to get it working:
old
```xml
<configuration type="Sitecore.ContentSearch.LuceneProvider.LuceneSearchConfiguration, Sitecore.ContentSearch.LuceneProvider">
...
<configuration ref="contentSearch/configuration/defaultIndexConfiguration">
...
<fieldMap ref="contentSearch/configuration/defaultIndexConfiguration/fieldMap">
```
new
```xml
<configuration type="Sitecore.ContentSearch.ContentSearchConfiguration, Sitecore.ContentSearch">
...
<configuration ref="contentSearch/indexConfigurations/defaultLuceneIndexConfiguration">
...
<fieldMap ref="contentSearch/indexConfigurations/defaultLuceneIndexConfiguration/fieldMap">
```

After these changes new config differs from SC75 with: index param named **propertyStore** and all nodes under **strategies** node.

**Comment by adeneys** [comment]
This is basically what I had as well with the inclusion of the strategies.
