### ISSUE TITLE
Experience Editor toolbar does not work in Sitecore 8.1 update 2

### ISSUE THREAD

**Issue by olivier-github** [WeTeam/WeBlog#158]
In Sitecore 8.1 update 2,
when you click on the buttons in the experience editor toolbar, nothing happens.

It works with Sitecore 8.0 update 7

**Comment by alan-null** [comment]
Thank you @olivier-github for the report.

I found what was the reason of the issue and created support package for you:
[WeBlog_support_158.zip](https://dl.dropboxusercontent.com/u/191345630/Stecore/WeBlog/support/WeBlog_support_158.zip).

Let me know if you encounter any problems.

**Comment by alan-null** [comment]
Merged.
