### ISSUE TITLE
SPEAK Components missing from module and repo

### ISSUE THREAD

**Issue by ddysart** [WeTeam/WeBlog#169]
Currently running a private build made from the develop branch and just started seeing these errors in the log:

4816 17:43:21 ERROR Error processing command url:/-/speak/request/v1/expeditor/ExperienceEditor.WeBlog.CanExecuteWeBlogCommands error:System.InvalidOperationException: Could not retrieve request class
 for url:/-/speak/request/v1/expeditor/ExperienceEditor.WeBlog.CanExecuteWeBlogCommands
   at Sitecore.Diagnostics.Assert.IsNotNull(Object value, String message)
   at Sitecore.ExperienceEditor.Speak.Server.RequestHandler.Process(HttpContext context)
   at Sitecore.ExperienceEditor.Speak.Server.RequestHandler.ProcessRequest(HttpContext context)
4556 17:43:21 ERROR Error processing command url:/-/speak/request/v1/expeditor/ExperienceEditor.WeBlog.IsEntryItem error:System.InvalidOperationException: Could not retrieve request class for url:/-/s
peak/request/v1/expeditor/ExperienceEditor.WeBlog.IsEntryItem
   at Sitecore.Diagnostics.Assert.IsNotNull(Object value, String message)
   at Sitecore.ExperienceEditor.Speak.Server.RequestHandler.Process(HttpContext context)
   at Sitecore.ExperienceEditor.Speak.Server.RequestHandler.ProcessRequest(HttpContext context)

It looks like the SPEAK componentry didn't make it into the repo and there is nothing in the data\serialization\core\sitecore\client folder.

**Comment by alan-null** [comment]
hi @ddysart 

Do you have [`WeBlog.ExperienceEditor.config`](https://github.com/WeTeam/WeBlog/blob/master/Website/App_Config/Include/WeBlog.ExperienceEditor.config) inside your App_Config/Include folder?

SPEAK Ribbon commands in Experience Editor were a part of previous public release. I assume everything should work fine.
My guess is that you probably did build for old version which do not include modern commands in Experience Editor (Page Editor previously).
![image](https://cloud.githubusercontent.com/assets/6848691/15377194/0a4e2956-1d5a-11e6-9fe4-5c35ea211d82.png)

Hope it helps.

**Comment by ddysart** [comment]
Bingo. Thanks
