### ISSUE TITLE
PageViews InterestingEntries isn't returning all entries from Facts_PageViews

### ISSUE THREAD

**Issue by sandyfoley** [WeTeam/WeBlog#170]
Attempting to use the InterestingEntriesAlgorithm = "PageViews" which runs a query against the Facts_PageViews table in analytics.

The query only returns a value--and only a single value--if the first ID in @EntryIds is in this table.

![webblog sql statement issue](https://cloud.githubusercontent.com/assets/2347061/15555575/50f806f0-2297-11e6-959d-dffbac7213c0.png)

In the image attached,  the first query for InterestingEntries was grabbed with SQL Profiler and it only returns one item.
The second query was manually changed to a NOT IN to prove that the other EntryId should have been returned as well.

This is for Sitecore 8.1 - WeBlog.2.4.0.for.Sitecore.8.0

**Comment by sandyfoley** [comment]
This is for Sitecore 8.1 - WeBlog.2.4.0.for.Sitecore.8.0

**Comment by alan-null** [comment]
hi @sandyfoley 
Thank you for investigation and report.
This issue has been already fixed by @adeneys here #118 and will be part of the next release.
