### ISSUE TITLE
Running WeBlog with Solr

### ISSUE THREAD

**Issue by kalotra** [WeTeam/WeBlog#172]
Hello.

Is it possible to run weblog with Solr? We're running Sitecore 8.1 Update 1 and using Solr and WeBlog conflicts with it. Any thoughts around this would be very helpful.

**Comment by alan-null** [comment]
Hi @kalotra 
I don't know if anybody from the team ever tested it. 
Current content search configuration has Lucene configuration only.
We would have to investigate that.

**Comment by adeneys** [comment]
Can you specify the nature of the conflict?

As @alan-null mentioned, the OOTB content search configuration for WeBlog is based on the Lucene content search configuration. If you've swapped your solution over to use SOLR then you'll need to adjust the WeBlog content search configuration to use SOLR as well. This shouldn't be too hard as the config is pretty basic, leveraging the default provider config for most things.

**Comment by kalotra** [comment]
Hello.
We decided to stick to Lucene for the content search so no problem with WeBlog now. However, we're having an issue submitting comment on PROD CD server. DEV CA/CD works fine. PROD CA works fine as well, but submitting comments from PROD CD returns following error:

"The request for security token could not be satisfied because authentication failed."

The configuration is same across servers accept the fact that PROD CD is running over https://. I can access http://[authoring server address]/sitecore modules/web/WeBlog/Comment.svc from PROD CD server. However, submitting comments from the CD node returns above error. I have advised the network team to double access between servers. Meanwhile, I'd appreciate any idea/suggestions from your side.

**Comment by adeneys** [comment]
The above issue is unrelated to SOLR, so please open a new issue for it.

I'll leave this current issue open until we add a SOLR specific config file.

**Comment by PavanOS** [comment]
If anyone wants SOLR configuration I did it and indexing worked for me. Shared the changed configuration, please download the attached file and remove .TXT extension
[WeBlog.ContentSearch.config.txt](https://github.com/WeTeam/WeBlog/files/756475/WeBlog.ContentSearch.config.txt)

**Comment by SMRaxa** [comment]
Hi Pavan,
I used your configuration file to switch to Solr but its not working, Its not indexing the contents of blog and Blog posts are not displaying, I checked all configurations and everything seems fine but I don't know where I made mistake and its not showing up. I am using WeBlog 3.0 and Sitecore 8.2 XP. Sitecore search with Solr is working fine, can you please let me know how can I troubleshoot. Thank you.

**Comment by SMRaxa** [comment]
Please find below the config files converted to Solr search.

[WeBlog.config.zip](https://github.com/WeTeam/WeBlog/files/785042/WeBlog.config.zip)

**Comment by hptbee** [comment]
Anyone fixed this issue ?

**Comment by PavanOS** [comment]
I did debug this issue a while ago , looks like the Solr query being sent by weblog code has issue, so it is not working even configs are right. So waiting for code fix.

**Comment by SMRaxa** [comment]
Yes, you are right. I also debugged it and got the same issue, so I copied the code of weblog and updated all of its queries into my solution.

**Comment by PavanOS** [comment]
SMRaxa, that's awesome. Can you please share the weblog code that you changed. You can email it to me at pavanomtri@yahoo.com

**Comment by hptbee** [comment]
I had change config, and solr can work in admin site.
But on page Blog in user site error.
Inner Exception: Value cannot be null. Parameter name: fieldNameTranslator.

@SMRaxa Can you share it here? Thanks you very much.

**Comment by SMRaxa** [comment]
I copied the GetBlogEnteries method from WeBlog solution and added it into my solution and updated it as below. I created my own controller/action which calls this method to fetch blog entries and then render the view.


`public IEnumerable<EntryItem> GetBlogEntries(string tag, string category, int maxNumber = MaxPosts, DateTime? minimumDate = null, DateTime? maximumDate = null)
        {
            
            var blog = Sitecore.Context.Database.Items[Templates.BlogHome.BlogId];//Blog ID
            

            List<EntryItem> result = new List<EntryItem>();
            var indexName = String.Format("sitecore_{0}_index", Sitecore.Context.Database.Name);

            if (!string.IsNullOrEmpty(indexName))
            {

                using (var context = ContentSearchManager.GetIndex(indexName).CreateSearchContext(SearchSecurityOptions.DisableSecurityCheck))
                {
                    var builder = PredicateBuilder.True<EntryResultItem>();

                    //var id = customBlogItem.BlogSettings.EntryTemplateID;
                    builder = builder.And(i => i.TemplateId == Templates.BlogEntry.BlogEntry);
                    builder = builder.And(i => i.Paths.Contains(blog.ID));
                    builder = builder.And(i => i.Language.Equals(blog.Language.Name, StringComparison.InvariantCulture));
                    builder = builder.And(item => item.DatabaseName.Equals(Context.Database.Name, StringComparison.InvariantCulture));

                    // Tag
                    if (!string.IsNullOrEmpty(tag))
                    {
                        builder = builder.And(i => i.Tags.Contains(tag));
                    }

                    // Categories
                    // This search is not working so I commented it for now, will check it later
                    //if (!string.IsNullOrEmpty(category))
                    //{
                    //    var categoryItem = ManagerFactory.CategoryManagerInstance.GetCategory(blog, category);

                    //    // If the category is unknown, don't return any results.
                    //    if (categoryItem == null)
                    //        return new EntryItem[0];
                    //    /*#if SC70
                    //                            var normalizedID = Sitecore.ContentSearch.Utilities.IdHelper.NormalizeGuid(categoryItem.ID);
                    //                            builder = builder.And(i => i.Category.Contains(normalizedID));
                    //    #else*/
                    //    builder = builder.And(i => i.Category.Contains(categoryItem.ID));
                    //    //#endif

                    //}

                    

                    if (minimumDate != null)
                        builder = builder.And(i => i.EntryDate >= minimumDate);

                    if (maximumDate != null)
                        builder = builder.And(i => i.EntryDate < maximumDate);

                    var indexresults = context.GetQueryable<EntryResultItem>().Where(builder);

                    if (indexresults.Any())
                    {
                        var itemResults = indexresults.Select(indexresult => indexresult.GetItem()).ToList();

                        //The above category filter was not working so I commented above and used this way because don't have time to configure index
                        if (!string.IsNullOrEmpty(category))
                        {
                            itemResults = itemResults.Where(item => GetCategories(item).Any(x => x.ToLower().Contains(category.ToLower()))).ToList();
                        }

                        result = itemResults.Where(item => item != null).Select(i => new EntryItem(i)).ToList();
                        result = result.OrderByDescending(post => post.EntryDate.DateTime).ThenBy(post => post.Created).Take(maxNumber).ToList();
                    }
                }
            }

            return result.ToList();
        }`

**Comment by AyushmatiVelir** [comment]
We need to change the Solr core names to remove capital casing i.e. use 'weblog-master' instead of 'WeBlog-master'.
This is because solr stores the _indexname field value(which is added in the query filter) as lowercase and solr querying is case sensitive(so the field value and index names don't match up in case of camel casing)

**Comment by varitw** [comment]
To fix the category issue, you need to add the following fieldmap into WeBlog.ContentSearch.config 

<fieldType fieldName="category" returnType="guidCollection"/>

**Comment by teggis** [comment]
After switching 'weblog-web' instead of 'WeBlog-web' I am now getting the error Index WeBlog-web was not found.  I cannot find where this is trying to call WeBlog-web.  Any Ideas where to search or anyone else having this problem

**Comment by AyushmatiVelir** [comment]
Please update the index name in WeBlog.ContentSearch.Web.config.
ex: <index id="weblog-web" type="Sitecore.ContentSearch.SolrProvider.SolrSearchIndex, Sitecore.ContentSearch.SolrProvider">

**Comment by teggis** [comment]
Yes I had already done that see below
id="weblog-web" type="Sitecore.ContentSearch.SolrProvider.SolrSearchIndex, Sitecore.ContentSearch.SolrProvider" 
I just cant find where it is calling the index by the capital case.

**Comment by varitw** [comment]
In WeBlog.config and WeBlog.delivery.config, there is a setting name
"WeBlog.SearchIndexName". You need to update the value to "weblog" (lower
case)

**Comment by teggis** [comment]
Thank you varitw that fixed the issue.

**Comment by teggis** [comment]
Is anyone have the issue with the tag cloud not returning posts when there is a multiple word tag?  It works in Lucene just find but with Solr it does not work.  Example is: "working today".  With solr click on "working today" returns nothing but Lucene brings backs post with this tag.  In Solr if you search by one or the other words "working" or "today" it returns posts. Any help will be appreciated.

**Comment by efezter** [comment]
Hi all 

I get 'Could not find add method: IncludeTemplate (type: Sitecore.ContentSearch.SolrProvider.SolrIndexConfiguration)' error after replacing WeBlog.ContentSearch.config with the file provided by @PavanOS. Any recommendation?

**Comment by andyram2k** [comment]
Hi,
We're upgrading to 9.2 currently, and with that we've updated the files to work with 9.2, and SOLR from Lucene. I've attached our config files which work with SOLR in case it helps anyone / the project team.

Andy

[weblog.zip](https://github.com/WeTeam/WeBlog/files/3743206/weblog.zip)

**Comment by alan-null** [comment]
Thank you, Andy (@andyram2k )

**Comment by djanjicek** [comment]
I have updated our 9.2 code base to all these changes (incl. commit #172), and now after rebuilding the indexes loading my page I get the following exception:

`[FormatException: Could not map index document field to property "Category" on type Sitecore.Modules.WeBlog.Search.SearchTypes.EntryResultItem : Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx). Actual value: {8AE09F4E-40CA-4AC3-BC17-51DF337CBB6C}|{EABEB6B2-41B3-4707-B156-64994831249C}]
   Sitecore.ContentSearch.DocumentTypeMapInfo.SetProperty(Object target, String propertyName, String documentFieldName, Object value) +1087
   Sitecore.ContentSearch.DefaultDocumentMapper`1.MapFieldValuesToType(IDictionary`2 fieldValues, TElement result, DocumentTypeMapInfo documentTypeMapInfo) +1841
   Sitecore.ContentSearch.DefaultDocumentMapper`1.MapToType(TDocument document, SelectMethod selectMethod, IEnumerable`1 virtualFieldProcessors, IEnumerable`1 executionContexts, SearchSecurityOptions securityOptions) +327
   Sitecore.ContentSearch.SolrProvider.<GetSearchResults>d__21.MoveNext() +291
   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +526
   System.Linq.Enumerable.ToList(IEnumerable`1 source) +69
   Sitecore.Modules.WeBlog.Managers.EntryManager.GetBlogEntries(Item blogRootItem, EntryCriteria criteria, ListOrder resultOrder)`

And here a cut from the actual index:

"category_sm":["{8AE09F4E-40CA-4AC3-BC17-51DF337CBB6C}|{EABEB6B2-41B3-4707-B156-64994831249C}"]

Does this look right?

**Comment by djanjicek** [comment]
![image](https://user-images.githubusercontent.com/3630988/70330926-c75cad00-183e-11ea-856c-648b30a2003a.png)

What's the difference between stringArray and stringCollection? Both are collections, but more interestingly, the Category property in EntryResultItem is ID[] and not string[] (like Tags).

**Comment by adeneys** [comment]
Hi @djanjicek,
This is what I'm working on now. Trying to get the category field to index and deserialize properly.
I'm not sure which commit you took as your link is to this issue, but I imagine it was one from the feature/172-solr-support branch. We use gitflow, so any feature branch is a work-in-progress.

**Comment by djanjicek** [comment]
Yes exactly, it’s the branch you mention. I’ll follow the progress on it,
as our client uses categories heavily and we need this one.

**Comment by djanjicek** [comment]
@adeneys Any progress so far?

**Comment by adeneys** [comment]
@djanjicek I've made a bit of progress and fixed the category issues, but I'm still validating.

**Comment by djanjicek** [comment]
@adeneys Thank you very much! This seems to work.

**Comment by adeneys** [comment]
Release 4.0 adds support for Solr when using Sitecore 9.x.
