### ISSUE TITLE
MVC Support?

### ISSUE THREAD

**Issue by ketchumj1** [WeTeam/WeBlog#173]
Hi,  

We are wanting to feature WeBlog components in a product we are building.   However, that product is primarily all MVC.   I saw numerous discussions about MVC support coming soon to WeBlog.   Do you know when this would be?    We may have to remove featuring WeBlog in our product until MVC support comes to the module.  

Thanks, 
Josh

**Comment by alan-null** [comment]
@ketchumj1 
I am afraid I cannot guarantee any date. All I can say it will be shipped with the next release.
We have to merge few small improvements and go through testing process to reach that goal.
