### ISSUE TITLE
Postlist, Archive and TagCloud not returning content  - Sitecore v8

### ISSUE THREAD

**Issue by BigBadD** [WeTeam/WeBlog#176]
I'm trying to run Weblog on a new Sitecore v8 upgrade, but Postlist, Archive and TagCloud are failing to return content.
The content all exists in the expected language variants and the WeBlog search index has been rebuilt.

Debugging GetBlogEntries, I can see that the template id, blog id etc are all valid and the query built looks correct... but nothing is being returned. If I modify the query to find a single blog item by ID, I still find that nothing is returned. Any ideas? I'm using the out-of-the-box config and dlls.

**Comment by adeneys** [comment]
It looks like we have a bug in the EntryManager constructor. The constructor has a default parameter but running on my local 8.1 instance I get an error in the log file about ReflectionUtil not finidng a default constructor. Obviously ReflectionUtil can't handle the default parameter when searching for the ctor to use.

As a workaround, try adding a default parameterless constructor to the EntryManager and see if that helps.

**Comment by adeneys** [comment]
Sorry, I spoke too soon. Running the 2.4 release package on new installs of Sitecore 8.0 and 8.1 and everything works fine.

Can you verify all blog items have been published to the web DB properly before rebuilding the WeBlog index? If everything is published, try using Luke to verify everything in the index looks correct.

**Comment by cmgutmanis** [comment]
Hi, I'm seeing the same issues as OP in an 8.1 instance. Could you confirm that the version in Sitecore marketplace and this repo is actually 2.4? When I decompiled the version from Marketplace as well as looked at the code in this repo, the assembly is listed as 2.3.0.x. Thanks!

**Comment by alan-null** [comment]
Hi @cmgutmanis 

>Could you confirm that the version in Sitecore marketplace and this repo is actually 2.4? When I decompiled the version from Marketplace as well as looked at the code in this repo, the assembly is listed as 2.3.0.x. Thanks!

We just forgot to update version number in `AssemblyInfo.cs` before the release
As you can see tag for 2.4 contains 2.3.0 in `AssemblyInfo.cs`
https://github.com/WeTeam/WeBlog/blob/release/2.4/Website/Properties/AssemblyInfo.cs#L34
