### ISSUE TITLE
Comments not visible on the website - Sitecore 8.0

### ISSUE THREAD

**Issue by baraamahroka** [WeTeam/WeBlog#178]
- Adding a comment from the website will add the item into the master DB and it will be visible in the "WeBlog Comments" workbox created section waiting to be submitted.
- Submitting the item is suppose to move the item from "Created" to "Awaiting Approval" to be approved but this is not happening from some reason making the item still invisible to the public.
- I made sure submitting item will trigger a publish command to add it to the web DB from the master DB but still invisible to the public.
- There is an issue with indexing as I was able to make the comment visible by rebuilding indexes for the WeBlog.

**Comment by baraamahroka** [comment]
Issue has been fixed on two different parts:

1- I fixed the workflow as it was not working properly to move like Created --> Awaiting Approval --> Approved.
2- The issue with the indexes was mainly because MongoDB was not installed on the production server. After installing MongoDB on prod; as soon as I approve the comment it will appear to the public.

**Comment by alan-null** [comment]
hi, @baraamahroka 

Great to see you've managed to fix your issues..
If you could provide us more details about fix for the first part we and whole community would be really grateful. 

As I see, current `Submit` button moves item to the next state which is `Approved` not `Awaiting Approval` but it is published.
I guess the only one problem here is missing step between `Submit` and `Awaiting Approval`, or is there something else?
