### ISSUE TITLE
Blog author name translates to Full Name in a ca environment but Fully qualified name in production

### ISSUE THREAD

**Issue by JenKove** [WeTeam/WeBlog#179]
Since an upgrade from 6.6 to 8.1 of Sitecore, using Weblog, we noticed that while preview and a test (content authoring) environment show the author's name on the blog page as (properly) translated to the Security Full Name, the items in production display as Fully Qualified name.  While I know I can manually change this author's name to text in all entries, the fact that it does translate nicely in ca inspires me to leave it and seek the fix.

## Dictionary Phrase/Key
We do have a dictionary weblog entry details item containing this phrase: 
by {1} | {0:MMMM d, yyyy} 

What does the {1} mean here and why is it represented differently in ca vs cd?

## Example of Differing Author From Same Post 
An example of this is:
### Content Authoring
http://ca.rmf.harvard.edu/Blog/2015/February/Safety-Salute-Ambulatory-Risk-Managers

Author displays as desired:
CRICO Blog
February Safety Salute | Ambulatory Risk Management Program
by **Katharine Schuler** | February 17, 2015
This February, we would like to deliver our Safety Salute to the [...]
vs.
### Production
https://www.rmf.harvard.edu/Blog/2015/February/Safety-Salute-Ambulatory-Risk-Managers 

Author displays the sitecore login username (or technically the "fully qualified name" from Security User manager)
CRICO Blog
February Safety Salute | Ambulatory Risk Management Program
by **RMFCORP\katharines** | February 17, 2015
This February, we would like to deliver our Safe[...]

**Comment by alan-null** [comment]
Hello @JenKove 

My first hint is to check **Full Name** in your *Sitecore User Manager*
![image](https://cloud.githubusercontent.com/assets/6848691/17040520/767ec842-4fa0-11e6-9da0-c97709783c54.png)

Compare it for the same user on both servers. I think on production value in this column is empty.

**Comment by JenKove** [comment]
You were 100% correct. Not only was it empty, but it was not even present. Thank you so much. I made a dummy entry for this domain user with the full name I wanted and it immediately appeared all over her blog posts. THANK YOU!

**Comment by alan-null** [comment]
@JenKove 
Great! I am glad I could help.
