### ISSUE TITLE
MVC Support?

### ISSUE THREAD

**Issue by jketchum1** [WeTeam/WeBlog#184]
Was there any updates with the WeBlog MVC Support?

**Comment by alan-null** [comment]
hi @jketchum1 

If you are asking about public release with MVC support. Answer is not yet.

MVC will be supported starting from the next release (3.0)

You can track release progress here:
https://github.com/WeTeam/WeBlog/milestone/2

6 issues left.
- 3 todo
- 3 done, waiting for review and merge

**Comment by adeneys** [comment]
Hi @jketchum1,
MVC implementation has been completed and is available on the develop branch. So if you can't wait for release 3.0, you can grab the source.

**Comment by jketchum1** [comment]
That is great news!   Thanks so much!    I am going to pull the latest now.

Thanks,
JOSH KETCHUM
Senior Software Engineer

NISH TECH, INC.
jketchum@nishtechinc.com<mailto:jketchum@nishtechinc.com> | www.nishtechinc.com<http://www.nishtechinc.com/>
