### ISSUE TITLE
WeBlog\ExperienceEditor\Commands in the package for 8.0 do not work for 8.1- here are replacements

### ISSUE THREAD

**Issue by ajmmurray** [WeTeam/WeBlog#199]
Files in the sitecore\shell\client\WeBlog\ExperienceEditor\Commands that are found in the package for version WeBlog-2.4.0_sc8.0 are designed for use with Sitecore 8.0.
When installed into a SC8.1 site you may find that the command buttons on the Experience Editor toolbar do not work and generate js errors.

Sitecore 8.0 and 8.1 want different JavaScript for Experience Editor ribbon buttons and client pipelines. 
In Sitecore 8.1, the Experience Editor script was refactored. 
Where before you had Sitecore.ExperienceEditor, now you have to load it as a dependency using RequireJs. 

The files attached here were all modified from the original in order that they should work with Sitecore 8.1.

All these scripts were modified to load the Experience Editor first, then to reference it without the Sitecore prefix.
[EditBlogSettings.js.txt](https://github.com/WeTeam/WeBlog/files/501959/EditBlogSettings.js.txt)
[EditEntrySettings.js.txt](https://github.com/WeTeam/WeBlog/files/501960/EditEntrySettings.js.txt)
[NewCategory.js.txt](https://github.com/WeTeam/WeBlog/files/501961/NewCategory.js.txt)
[NewEntry.js.txt](https://github.com/WeTeam/WeBlog/files/501962/NewEntry.js.txt)

(change the suffix by removing the .txt extension before using)

Perhaps these files can be used when a Sitecore 8.1 specific package is prepared.

**Comment by alan-null** [comment]
Hello @ajmmurray,

Thank you for report.
I believe issues you are talking about were fixed already: #158
