### ISSUE TITLE
Question: MVC install - best way?

### ISSUE THREAD

**Issue by kmac23va** [WeTeam/WeBlog#201]
I'm beginning installation and usage of WeBlog on an MVC 8.1 U2 site. I've seen several questions through the backlog about the MVC version, where someone said in August it was pretty much ready in the develop branch. I grabbed the source code, filled in the missing references from the Sitecore NuGet feed, and built it out using the Release-sc80 configuration, which seemed to work.

Is the best way to simply grab the WeBlog and WeBlog.MVC DLLs and put them in my project, along with the static files, then deserialize the items in the serialization folder into Sitecore? Should I do this without first installing the WeBlog package, or should I do it on top of that? Or, is there hope there's a package coming out shortly, even if it's just downloaded from here?

Thanks much.

**Comment by kmac23va** [comment]
As a note, when I try to import a number of the serialization items, I'm getting "Length of field content does not match the content-length attribute." errors on some fields.

**Comment by alan-null** [comment]
Hello @kmac23va,

Here is how I setup new dev machine
* create clean Sitecore instance
* checkout code
* configure `deploy.targets` file 
* setup serialization folder
  * create junction for serialization folder / copy serialization folder to website data folder
  * merge folder `master-rdb-additional` into `master` 
* run build with desired build configuration
* update db
 * open `http://domainsitecore/admin/serialization.aspx`
 * update core, master databases
* Setup Theming (details can be found in `how to build.md`)

If you have any questions do not hesitate to ask.

**Comment by kmac23va** [comment]
The serialization step runs into "length of field content does not match the content-length attribute" errors. I know I've run into a couple when I tried to do it through the content editor, here I get the YSOD directly. The first is in core on serialization\core\sitecore\client\Applications\WeBlog\Import.item, the __Renderings field; another is in master on serialization\master\sitecore\templates\Modules\WeBlog\WebForms\BlogEntry.item, the __Renderings fields. Unfortunately it doesn't show a list of all failures at once like a log, so I can only get the next one after the previous is handled.

I'm hooking into Sitecore 8.1 Update 2 for this; the deploy.targets step worked perfectly to the directions.

Thanks.

**Comment by alan-null** [comment]
@kmac23va  I just recreated environments two times: one with pre-installed package, then with clean db and I cannot reproduce that (tried with Update 3 but I don't this is the issue).

Could you please find that item which cannot be deserialzied and attach here?
Or please validate it by yourself. My guess is that you have some local changes or your website looks for item in wrong directory (make sure your website has correct data folder location setting value).

You can validate field like that:
![image](https://cloud.githubusercontent.com/assets/6848691/19051327/e1e630c4-89b2-11e6-9174-762004d4c5fc.png)
Is the content the same as here:
https://github.com/WeTeam/WeBlog/blob/develop/data/serialization/core/sitecore/client/Applications/WeBlog/Import.item
?

Just to make sure, you are trying to setup this with develop branch right?

**Comment by kmac23va** [comment]
@alan-null Yes, this is off the develop branch - my main goal is to get the MVC setup in place. I haven't made any changes to the project or files...the first couple of times I was trying to restore/connect up the bin files manually, but after you pointed out the deploy.targets bit I ran exclusively from there with a clean starting point.

I confirmed I'm using the exact same file you linked to. Interestingly though, your version is different from mine...I show 1979 characters when I do the select check on the __Renderings field, and 3449 in the total file length. I can go in and make appropriate adjustments (I hadn't seen that select bit before in Notepad++), but I just downloaded the develop branch into a zip yesterday.

I did find one difference that looks key, and maybe it's because I downloaded via a zip file from Github instead of grabbing the source through Visual Studio. When I opened the .item file in Notepad++, it was in Unix format, and I see yours is in Dos\Windows format. When I changed the format, my field count matched yours. Odd that it makes that much of a difference, but let me see about grabbing the files another way or saving the format differently and seeing how that works.

**Comment by kmac23va** [comment]
Yep, that did it...each time I came across an error, I changed the format to Dos\Windows and saved the file, and got past it. It wasn't a lot of them, but I was able to get everything serialized in. I'll let you know if anything else comes up...thanks much.

**Comment by alan-null** [comment]
No problem, good luck @kmac23va.

**Comment by kmac23va** [comment]
One issue I ran into after getting everything set up was, in experience editor, there were some errors in edit mode around invalid HTML. I tracked it down some and it looks related to either the comment submission form or the captcha. What I ended up doing was wrapping those in checks to only show them if not in experience editor or preview mode (since they aren't needed there).

It also seemed like the New Entry button in the experience editor ribbon wasn't working fully - the item would be created but I wasn't navigated over to it - but I wanted to recheck that first. I'll keep you posted.

**Comment by adeneys** [comment]
Thanks for your input @kmac23va. Could you please open new separate bugs for each of those issues you found? The one about invalid markup in EE and the new entry button? We're just wrapping up dev at the moment so if we can identify and squash these bugs before release, that would be great.

And just a note on the item line endings. Rather than downloading the source from github into a zip I would suggest using a git client to clone the repository. Your git client can typically handle things like line ending conversion (different between a UNIX text file and a Windows/DOS text file).
