### ISSUE TITLE
New Entry button does not redirect

### ISSUE THREAD

**Issue by kmac23va** [WeTeam/WeBlog#203]
I'm seeing this in 2.4 and the develop branch, applying the patch from #158 in 8.1 update 2. When I click New Entry, I get the popup to fill in my title, but when I click OK, I was expecting to be redirected to the new entry to fill it out. The entry is created, I see it in Content Editor and it shows up in the navigation bar in Experience Editor, but I'd thought I'd be sent to that page.

**Comment by kmac23va** [comment]
I'm not sure if you can see the fork I did of the project, but I made a fix for this into my develop branch.

**Comment by alan-null** [comment]
@kmac23va I created separate branch and pull request for each issue.
Once your fixes will be reviewed and accepted we will merge it to develop branch.

Pull request for this issue can be found here: #210

If you wish submit any fixes in the future please read [Contributing](https://github.com/WeTeam/WeBlog/wiki/Contributing) section in our wiki.
