### ISSUE TITLE
Settings buttons do not auto refresh?

### ISSUE THREAD

**Issue by kmac23va** [WeTeam/WeBlog#204]
I'm seeing this in 2.4 and the develop branch, applying the patch from #158 in 8.1 update 2. When I change settings for a blog or an entry using the Experience Editor buttons and click OK, nothing appears to happen. The save button is grayed out, but I know the changes are taking affect, I just need to refresh the page to see the changes. I'm not sure if this is the expected behavior or not, but thought I'd bring it up.

**Comment by alan-null** [comment]
@kmac23va 
Yes, you are right, this is how it works now. 
Refresh functionality was never implemented.

I think we should do this for both settings buttons.

**Comment by alan-null** [comment]
@kmac23va 
Would you like to implement this enhancement?

**Comment by kmac23va** [comment]
This one I don't have a sample near me to work up, so pass. :) I had to do some rewiring on my version of the code to get things working as needed with my project (tags on PostListEntry, a way to call the Entry model from a non-blog page and thus need to set CurrentBlog manually)...I'll have to see about re-integrating them at some point.
