### ISSUE TITLE
MVC Entry in edit mode throws errors

### ISSUE THREAD

**Issue by kmac23va** [WeTeam/WeBlog#205]
Using 8.1 update 2 with the develop branch MVC code. Using the default entry setup, when I bring up the entry in Experience Editor edit mode, I get errors around the captcha component (see image). As a note, when I remove the captcha component from the page, the Sitecore error disappears, but the raw HTML showing up for the comment form still appears. (The other raw HTML appears to be the Facebook button, which doesn't seem to render at all in preview/normal mode.)

My suggestion for a fix, that I'm personally implementing, is to wrap the "add a comment" form in a check if the page is in edit or preview mode and to not display the comment form then (since it wouldn't be needed). This would encompass the captcha as well, since it's on a placeholder in the form.

<img width="1440" alt="screen shot 2016-10-08 at 7 39 15 am" src="https://cloud.githubusercontent.com/assets/3249118/19212905/38453e62-8d2b-11e6-8824-885b931a914d.png">

<img width="1440" alt="screen shot 2016-10-08 at 7 56 23 am" src="https://cloud.githubusercontent.com/assets/3249118/19212949/c44cf19c-8d2c-11e6-9061-ed3321b4358d.png">

**Comment by kmac23va** [comment]
I'm not sure if you can see the fork I did of the project, but I made a fix for this into my develop branch.

**Comment by alan-null** [comment]
@kmac23va I created separate branch and pull request for each issue.
Once your fixes will be reviewed and accepted we will merge it to develop branch.

Pull request for this issue can be found here: #209

If you wish submit any fixes in the future please read [Contributing](https://github.com/WeTeam/WeBlog/wiki/Contributing) section in our wiki.
