### ISSUE TITLE
"Load more" functionality

### ISSUE THREAD

**Issue by kmac23va** [WeTeam/WeBlog#207]
I noticed that the "load more" formatting functionality always uses the default PostListEntry format, even if an alternate form was entered into the PostList rendering parameter. Not a big deal but is there a way to make it respect the rendering parameter entry?

**Comment by alan-null** [comment]
@kmac23va 
It happens because entries for load more purposes are requested via different device.
There is different post list there, so you need change values twice.
See screenshot:
![image](https://cloud.githubusercontent.com/assets/6848691/19224183/c7e7f1ee-8e80-11e6-8d36-4188b854b2b6.png)

**Comment by kmac23va** [comment]
Ah, that's the reason for the device. Very good, thanks!
