### ISSUE TITLE
Index in not updated after new item is added.

### ISSUE THREAD

**Issue by alan-null** [WeTeam/WeBlog#212]
### Steps to Reproduce the Problem
  1. Create enthronement using develop branch
  1. Rebuild indexes
  1. Create new blog
  1. Add new Entry
  
### Expected Behavior 
After item is added index should be auto updated.

### Actual Behavior
Item added, index not updated. New entry does not appear in post list

### Specifications
Sitecore.NET 8.1 (rev. 160519)

**Comment by adeneys** [comment]
The cause of the issue is the cache settings on the sublayout definition item. These need to be updated.

**Comment by adeneys** [comment]
Sublayout and view definition item cache settings were updated to ensure they are correct. This issue is no longer reproducible for me locally. Tested on Sitecore 8.0 and 8.1.
