### ISSUE TITLE
Blog Entry doesn't show up after publishing 

### ISSUE THREAD

**Issue by allanChacon** [WeTeam/WeBlog#222]
Hi, new blog entry doesn't show up after publishing. I tried to rebuild indexes, reset IIS, clear sitecore cache, republish the site but the blog entry is not there but if I create a new one then I can see the first entry that I created. I'm using Sitecore 7.5 and WeBlog-2.4.0_sc7.5

I think is related with this issue: https://github.com/WeTeam/WeBlog/issues/38

Thanks. Any help would be appreciate it.

**Comment by alan-null** [comment]
Hi @allanChacon 
What about the next posts? As I understood you were able to get it working when you created another, right?

When you created the next one did you check it on `web` or `master`? Did both posts appear or only the first one, but the last you created did not?

We are very close to release of the next major version. Is it a blocker for you or something that could wait?

**Comment by allanChacon** [comment]
Hi,

Correct, I was able to get it working when I a created another. Both are in master and web so I tought the problem was indexes so I tried rebuild everything. 

For now, it's not a block so I can wait. Will this major version able for Sitecore 7.5? 

Thanks for your help

**Comment by alan-null** [comment]
Our plan is to support every version starting from **Sitecore 7.2** .

Some packages might appear earlier than the other. 

The highest priority have version: 8.1 and 8.2 but we are going to release the rest for sure.

**Comment by alan-null** [comment]
Hello @allanChacon,

We have released [3.1](https://github.com/WeTeam/WeBlog/releases/tag/release/3.1) some time ago. 
If you encounter any issue with the most recent code please raise a new issue.
