### ISSUE TITLE
Missing reporting items in WeBlog 8.2 package

### ISSUE THREAD

**Issue by alan-null** [WeTeam/WeBlog#224]
### Steps to Reproduce the Problem
  1. Install Sitecore 8.2
  1. Install WeBlog for Sitecore 8.2 package
  1. Create new blog
  1. Open Blog/Entry in experience editor
  
### Expected Behavior 
no errors

### Actual Behavior
`There is no item with ID 9BECF823-2838-467C-87A7-3664524F5AFE`

![image](https://cloud.githubusercontent.com/assets/6848691/20730771/9d53a1b0-b687-11e6-912f-7e7cc3d1184d.png)

### Specifications
**Sitecore:** Sitecore 8.2 rev. 160729.zip
**WeBlog:** WeBlog-3.0.0_sc8.2.zip

**Comment by BEPTEP** [comment]
Where can I find WeBlog for Sitecore 8.2 ?

**Comment by alan-null** [comment]
Hello @BEPTEP,
It was not released yet, we are currently at the final phase before release.

Once we release it you will find packages here: 

* **Marketplace:**
https://marketplace.sitecore.net/Modules/W/WeBlog.aspx?sc_lang=en
* **Github repository:**
https://github.com/WeTeam/WeBlog/releases

**Comment by BEPTEP** [comment]
Alan, thank you for the prompt response! Any ETA?

**Comment by alan-null** [comment]
We are currently testing release packages and everything looks promising.
We need to close all these issues:
https://github.com/WeTeam/WeBlog/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22release+3.0%22
before the release. Cannot say anything more

**Comment by BEPTEP** [comment]
Alan, may I offer you a hand to facilitate the release?

**Comment by alan-null** [comment]
@BEPTEP Thank you. We have only one issue to solve. 
If you want you can always create your dev instance (using `develop` branch) and test it if you want.

**Comment by adeneys** [comment]
Added the report query items to the package
