### ISSUE TITLE
Wordpress import. Error while importing comments

### ISSUE THREAD

**Issue by alan-null** [WeTeam/WeBlog#227]
### Steps to Reproduce the Problem
  1. Open Wordpress import wizard
  1. Select attached file
  1. Import
  
### Expected Behavior 
Blog successfully imported without any issues.

### Actual Behavior
Error during importing one of the comments.

### Additional info
Special words/characters present in a path for a fast query should be escaped.

You can verify this here: `http://domain/sitecore/shell/default.aspx?xmlcontrol=IDE.XPath.Builder`

**Query:**
`/#sitecore#/#content#/#Home#/#r1#/#2016#/#December#/#Mile Post#/Comment at 20161219 174023 by True Religion#`
**Result:**
`End of string expected at position 93.`

**Query:**
`/#sitecore#/#content#/#Home#/#r1#/#2016#/#December#/#Mile Post#/#Comment at 20161219 174023 by True Religion#`
**Result:**
`The query did not return any items.`

**Comment by adeneys** [comment]
Merged
