### ISSUE TITLE
Lack of name validation for NewEntry, NewCategory EE ribbon commands

### ISSUE THREAD

**Issue by alan-null** [WeTeam/WeBlog#229]
### Steps to Reproduce the Problem
  1. Open EE
  1. Click `New Entry`/`New Category` button
  1. Try two scenarios
      * Do not type anything, leave input empty
      * Type some forbidden characters
  
### Expected Behavior 
You should see validation message if you type incorrect characters.

### Actual Behavior
* if you pass empty value you will see error message (server error)
* no validation.

**Comment by adeneys** [comment]
Merged
