### ISSUE TITLE
How to upgrade weblog for sitecore 8.2

### ISSUE THREAD

**Issue by jaideep-charan** [WeTeam/WeBlog#233]
I have upgrade my sitecore site from 8.0 to 8.2 now i want to upgrade weblog.

**Comment by adeneys** [comment]
We're still in the process of getting the 7.x packages for WeBlog 3.0 done, and then we'll be moving onto an upgrade guide. Given this release made quite a few breaking changes this guide will be a necessity.

**Comment by hombreDelPez** [comment]
Hi @adeneys 
Any news about the upgrade guide? Because right now we are upgrading our 8.1.2 Sitecore solution to Sitecore 9.0.2 and also need to make the WeBlog module work again. We still have some issues regarding the javascript used for the WeBlog experience editor buttons in the ribbon.

**Comment by adeneys** [comment]
Sorry it took so long, but I've just updated the Installation Guide wiki Page https://github.com/WeTeam/WeBlog/wiki/Installation-Guide.

Please let me know if something is missing.
