### ISSUE TITLE
Missing fields in WeBlog 3.0 package

### ISSUE THREAD

**Issue by PavanOS** [WeTeam/WeBlog#234]
We are starting fresh with WeBlog (never used it before) 
We downloaded WebBlog 3.0 and installed it on our Sitecore 8.2 instance 
We noticed some things are not working, blog entry page body was empty , categories & tags were not working. Upon digging intro code and packages I found the following custom fields on BlogEntryItem template were missing.

CustomCheckboxField - "Disable Comments"
CustomDateField - "Entry Date"
CustomImageField - "Image"
CustomImageField - "Thumbnail Image"
CustomMultiListField - "Category"
CustomTextField - "Author"
CustomTextField - "Content"
CustomTextField - "Introduction"
CustomTextField - "Tags"
CustomTextField - "Title"

 Can you please provide us corrected completed package ?

Thanks
Pavan

**Comment by alan-null** [comment]
Hello @PavanOS,

Are you sure that you have used appropriate templates/branches?

During installation, we provide following details

```
[...]
Create a Blog
=============
* Create a new blog using one of the following branches:
    - 'Modules/WeBlog/Blog WebForms' for WebForms
    - 'Modules/WeBlog/Blog MVC' for MVC

[...]
```

In order to create a new blog please use following branches:
* WebForms `/sitecore/templates/Branches/Modules/WeBlog/Blog WebForms`
* MVC `/sitecore/templates/Branches/Modules/WeBlog/Blog MVC`

**Comment by PavanOS** [comment]
Yes I did you the suggested templates that created BlogHome , BlogEntries & categories etc., 
Then I created Blog Entry item by right clicking on blog home, that item is missing fields.
The fields are missing in the template itself. I do see those fields in you package under 
WeBlog-3.0.0_sc8.2.zip\package.zip\items\master\sitecore\templates\Modules\WeBlog\Base\BlogEntry

But I think the package is missing FieldTypes that should be going into "core" database.
As far as I know those custom field type definition items must be present in CORE db under /sitecore/system/Field types , that branch is totally missing in your package. Can you please check and update the package.

**Comment by alan-null** [comment]
@PavanOS 

Not really. You are right, we have an additional abstraction in our code (for example: `Sitecore.Modules.WeBlog.Data.Fields.CustomTextField`
but this is something different from field types definition in Sitecore.

You can see that in facts all WeBlog fields use default Sitecore field types
[Title field of BlogEntry template (Single-Line Text)](https://github.com/WeTeam/WeBlog/blob/master/data/serialization/master/sitecore/templates/Modules/WeBlog/Base/BlogEntry/Entry/Title.item#L18)

You should also see it when you unpack any xml file and check fields definitions:

```xml
<item name="Title" key="title" id="{A99A1591-F367-48A0-8900-E5DCBC8B528F}" tid="{455A3E98-A627-4B40-8035-E683A0331AC7}" mid="{00000000-0000-0000-0000-000000000000}" sortorder="100" language="en" version="1" template="template field" parentid="{0297A5B4-EAF4-4B5B-BDAD-23D802F6F9CB}">
    <fields>
        <!--other fields-->
        <field tfid="{9541E67D-CE8C-4225-803D-33F7F29F09EF}" key="__short description" type="text">
            <content>Enter the title of your blog entry</content>
        </field>
        <field tfid="{19A69332-A23E-4E70-8D16-B2640CB24CC8}" key="title" type="text">
            <content />
        </field>
        <field tfid="{BA3F86A2-4A1C-4D78-B63D-91C2779C1B5E}" key="__sortorder" type="text">
            <content>100</content>
        </field>
        <!-- Title Field field type Single-Line Text -->
        <field tfid="{AB162CC0-DC80-4ABF-8871-998EE5D7BA32}" key="type" type="Grouped Droplist">
            <content>Single-Line Text</content>
        </field>
    </fields>
</item>
```

We tested everything before release, just in case I downloaded the current 3.0 package and installed it on my fresh instance, without any problems.

Ok let's try to find out what is wrong, 

1. Have you looked into Sitecore logs after installation? Are there any errors during installation?
1. Have you tried to reinstall WeBlog on the same/different instance/machine?
1. Do you have other modules installed?

**Comment by PavanOS** [comment]
I downloaded again and reinstalled, I did not see any errors. I did see above mentioned fields getting installed in the log. So that is not issue , but found a different issue. The above list of fields is defined on 
/sitecore/templates/Modules/WeBlog/BlogEntry  , which is configured as insert option on WebForms BlogHome item. So WebForms version should work as expected I am yet to test.

Where as MVC BlogHome item is tied to /sitecore/templates/Modules/WeBlog/MVC/BlogEntry , which only inherits BlogEntryBase which doesn't contain any fields.

**Comment by alan-null** [comment]
> The above list of fields is defined on
/sitecore/templates/Modules/WeBlog/BlogEntry 

The current release package doesn't contain an item with that path.
Your templates should look like this
![image](https://cloud.githubusercontent.com/assets/6848691/22818390/4635678c-ef6d-11e6-9f8f-20c79b12d5f6.png)

Let's try something:
Could you search for following items by ID:
* `{BE9675B1-4951-4E11-B935-A698227B6A97}`
* `{857FD02F-D166-42CC-944B-C97159A259AA}`
*  `{A99A1591-F367-48A0-8900-E5DCBC8B528F}`

Let me know if you can find all of them and paste item path of each.

I didn't get an answer for my previous question:

> 3. Do you have other modules installed?

**Comment by PavanOS** [comment]
No I have not installed any other module , I did first install WeBlog from market place , the I realized it is not compatible with Sitecore 8.2 and went ahead and manually cleanup the items installed by that older package. After that I downloaded WeBlog 3.0 from guthub and installed it with Merge-Merge option for items.

That may have messed up these fields parent item. I re-installed the package with Overwrite option for items. That fixed the issue. Now MVC template working fine.

You may close this issue.
