### ISSUE TITLE
Post list for a category is not working with Solr indexes

### ISSUE THREAD

**Issue by PavanOS** [WeTeam/WeBlog#235]
I am using WeBlog 3.0 on Sitecore 8.2, I created blog using WebForms branch template. And those items made it to the solr indexes fine. When I click on category link, category page loads fine , but it was not showing the posts list tagged with that category. 

I found this error in search logs.
```
 628 22:48:02 INFO  Serialized Query - ?q=((((_template:(5fa92ff44ac248e292ebe1e4914677b0) AND _path:(c3a4b84107dd4534a331543293d9c2c6)) AND _language:(en)) AND _database:(master)) AND category:(8aef1500faf543fe92f039bbabf04e10))&rows=0&fq=_indexname:(WeBlog\-master)
 628 22:48:02 ERROR Solr Error : ["undefined field category"] - Query attempted: [((((_template:(5fa92ff44ac248e292ebe1e4914677b0) AND _path:(c3a4b84107dd4534a331543293d9c2c6)) AND _language:(en)) AND _database:(master)) AND category:(8aef1500faf543fe92f039bbabf04e10))]
```

I noticed that solr fields are created with field type suffix , in this case category field on solr index is created as category_sm. But above generated query is not taking this into account. 

So please let me know is there something we can do to use this module with Solr indexes.

**Comment by alan-null** [comment]
We do not provide official Solr configuration yet. 
Solr is on our to-do list (#172).

**Comment by PavanOS** [comment]
Any idea of possible date, so that we can decide to wait or look for alternatives

**Comment by alan-null** [comment]
I cannot promise anything. Current release is still in progress as we did not release WeBlog 3.0 for Sitecore 7.X

**Comment by JanVorster** [comment]
Is there any version of WeBlog that is compatible with a Sitecore 8.1 instance running with Solr?

**Comment by alan-null** [comment]
@JanVorster 
Solr is not yet supported.

**Comment by AyushmatiVelir** [comment]
I am getting the same issue and on checking the logs I see "undefined field category"

**Comment by adeneys** [comment]
Closing this issue as SOLR support is officially being added in issue #172 .
