### ISSUE TITLE
Blog Entry doesn't show up in Experience Editor/Preview

### ISSUE THREAD

**Issue by somaraghuveer** [WeTeam/WeBlog#236]
The issue I am facing is, a newly created Bucketable Blog Entry, does not show up in the Page Editor or Preview mode.  I am using EntryManager.GetBlogEntries(ID blogID, Database database, int maxNumber).
Examining the Index Statistics on the Index Manager, I noticed varying Document Counts in the below scenarios, which makes me think of a possible **BUG** in the Blog Entry item creation process of the WeBlog 2.5 module. 

Before Blog Entry item Creation:
sitecore_master_index :: Document Count : 34046
WeBlog:: Document Count : 3581

After Blog Entry item Creation:
sitecore_master_index :: Document Count : 34047
WeBlog :: Document Count : 3581
Issue: I do not see the Newly created Blog Entry in the Experience Editor/ Preview modes.

And after a ReBuild of the Index, the Blog Entry items shows up in Experience Editor/ Preview modes and the Document Counts are updates as shown below:
sitecore_master_index :: Document Count : 34047
WeBlog :: Document Count : 3582

I feel this as a BUG, as the Content Authors should not be able to Rebuild every time a New item is created.

**Comment by alan-null** [comment]
Hi @somaraghuveer 
Currently, supported version is [3.0](https://github.com/WeTeam/WeBlog/releases/tag/release%2F3.0)
As WeBlog utilize search indexes to serve content, indexes have to be rebuilt everytime new entry is added.
