### ISSUE TITLE
creating a new Blog Entry item, Unchecks the Bucketable checkbox on the Entry Item

### ISSUE THREAD

**Issue by somaraghuveer** [WeTeam/WeBlog#237]
When I try to create a new Blog Entry item, a pop -up asks me to enter the name of the Item > Click OK. Another dialog pop-up asking Do you want to save the changes to the item? with options Yes No Cancel. When I say Yes, it Unchecks the Bucketable checkbox on the new Blog Entry item.
When I say No, it keeps the Bucketable checkbox as mentioned in my Standard Values of the template.

1. Why does the second dialog Message pop-up? 
2. Why does it Uncheck the Bucketable checkbox on the Blog Entry item when Yes is selected to save changes on the Blog Root Item, because it shows **Unbucketable Item stored in an Item Bucket** warning message on the newly created blog Entry item, and I don't want that to happen?

Is this a bug or that's how the WeBlog module works?

**Comment by alan-null** [comment]
Hello @somaraghuveer,

Sorry for late response. Nothing that you described should ever happen.
I installed fresh instance for Sitecore 8.2 yesterday and I couldn't reproduce your issue.

To fully understand what could be the reason of your issues, could you please provide detailed steps to reproduce?

* Which Sitecore version are you using (revision number would be helpful)
* Which version of WeBlog have you installed
* Is it a clean instance with WeBlog (module installed for the first time) or updated?
* Do you have any other modules installed or any custom code?
* Did you modify any of default WeBlog templates?

**Comment by somaraghuveer** [comment]
Thank you for your response.
Sitecore 8.1 update 2
WeBlog 2.5 i believe.
It was not a clean install, it was an update to the (wrong version) installed.
modules like WFFM , AD module, Sharepoint and CRM connectors installed.
We have not modified any default.

I believe there is no support for WeBlog 2.5. Hence closing.
