### ISSUE TITLE
WeBlog entries prompting a save action immediately upon creation

### ISSUE THREAD

**Issue by ECYR-TG** [WeTeam/WeBlog#241]
We're having an issue after a fairly extensive sitecore upgrade (including weblog versions) when creating a new blog entry. Right after clicking the blog item, creating a new entry, and naming it, a Sitecore save confirmation window will appear. This would be only a slight nuisance, but if you accept the save it clears out the bucketable settings of the item which gives an error and confuses our client. Is there some known mechanism that would execute on create and reset these standard values? I've looked through the configuration and there doesn't seem to be anything related to item creation outside of moving the file to the correct subfolder.

**Comment by alan-null** [comment]
Which install options have you used during installation? **Overwrite** should do the job. Perhaps you used **Merge** and there are some integration issues.

If this not the case please provide complete steps to reproduce/as many details that could help us to reproduce this issue and provide solution.
* old Sitecore version
* new Sitecore version
* old WeBlog version
* new WeBlog version
* order of upgrade steps

Related: #237

**Comment by amir-begic** [comment]
Hi!

I've been encountering the same issue and I don't think it has to do anything with the upgrade. I'm using WeBlog 3.10 on a Sitecore 8.1 rev. 160302 (8.1 Update-2). 
The save dialog only appears when the "Standard fields" checkbox (Content Editor -> "View"-Ribbon) is activated. If you answer the overwrite dialog with "Yes", the item is created and loses the Item Buckets standard values. :( At least other standard values, for example "Disable Comments", are not affected by the issue.
I've tested the whole thing on a fresh Sitecore 8.1 Update-2 SIM install and it behaves the same as it does within our customers Sitecore instance.

As a workaround we could advise the authors to disable the checkbox, but I'd really like to find a better solution than that. If you need any

**Comment by hombreDelPez** [comment]
@amir-begic

Hi, I also encountered this behaviour.
After extensive "bug hunting" I discovered that this seems to be a bug in Sitecore 8.1 Update 2. Once you change the bucket path this dialog window pops up. And it doesn't matter if you do it with the Sitecore config or with a bucket rule.

**Comment by adeneys** [comment]
Closing this issue as the above comments indicate it's related to Sitecore 8.x which is no longer supported.
