### ISSUE TITLE
Disappearing Blogs

### ISSUE THREAD

**Issue by gadgetman110** [WeTeam/WeBlog#242]
We have been seeing an intermediate issue with Blogs when Publishing in Sitecore 8.1.  Sometimes when an Author publishes a new Blog, all the Blogs on the list page "disappear".  Doing a Republish does not seem to help.  We have been having to switch the Layout, Publish, then switch the Layout back to what it was and Publish again to get the Blogs "back".  We have been having this occur for 2 weeks but unfortunately have not been able to replicate the issue "at will".

We wanted to throw this out on the chance that you had any ideas we could try or if you have seen the behavior before.

**Comment by alan-null** [comment]
Hi @gadgetman110,

If this is not a problem you can try to disable caching for this component and give a little bit of time to show whether caching is an issue in this case.

**Comment by gadgetman110** [comment]
Thank you for the reply.  Where do I disable caching for this component?


________________________________

**Comment by gadgetman110** [comment]
I checked all the controls (sub layouts) for this and nothing is marked as chacheable.  Were you meaning something else?

**Comment by gadgetman110** [comment]
Hello.  Here is some more data that may help.  We have been using WeBlog for quite some time and with earlier versions of Sitecore.  Buckets did not exist.  When we upgraded to Sitecore 8.1 WeBlog "broke" and we had to upgrade WeBlog as well.  We DO notice that we see this message in Sitecore.  Unbucketable Item stored in an Item Bucket
This item is stored in an item bucket. However, it is not hidden because its template is not bucketable. If you want to hide this item in an item bucket, you must make the template that is based on bucketable.

So WeBlog out of the box is now bucketable but our older content is not.  Is this or could this be an issue?  I don't want to just change it, in fact we can't just do that as that will change a lot of URL's that we would have to recreate redirect rules for.  

But I wanted to know if this could be a known issue that may cause what we are seeing?

**Comment by alan-null** [comment]
@gadgetman110 

### Caching
Caching settings are stored in several places in Sitecore, take a look here:
![image](https://cloud.githubusercontent.com/assets/6848691/24765810/84ccad86-1af9-11e7-9ea3-27c4fccc6b47.png)

mvc rendering: `/sitecore/layout/Renderings/WeBlog/MVC/PostList`
web forms sublayout: `/sitecore/layout/Sublayouts/WeBlog/PostList`

### Buckets
Regarding buckets options. I imagine that upgrade might introduce some issues.
If you could provide more details (previous/current Sitecore, WeBlog versions). I could try to reproduce it and give you a solution.

If you can test it by yourself you can try to change the items template. I guess you've got wrong templates in your content right now.

Make sure that all items under content node use templates from either:
`/sitecore/templates/Modules/WeBlog/MVC`
or
`/sitecore/templates/Modules/WeBlog/WebForms`
folders.

Please make sure you backup your solution first to prevent losing any data.

**Comment by gadgetman110** [comment]
Here are some details.  We were on sitecore 6.6 then sitecore 7 then sitecore 8 with weBlog version 2.3.
We are now on sitecore 8.1 and upgraded to 3.0 weBlog.

**Comment by alan-null** [comment]
@gadgetman110 

I've created a content with WeBlog 2.4 for sc 7.0, then installed it on 
the fresh instance with Sitecore 8.1 + WeBlog 3.1.

There are few manual steps, but everything else works fine.

### Categories item
![image](https://cloud.githubusercontent.com/assets/6848691/24830966/7d0f3166-1c90-11e7-8609-dc907fb1cca8.png)

### Posts

![image](https://cloud.githubusercontent.com/assets/6848691/24830987/f25bf6b6-1c90-11e7-9cbf-4bb3b7466e74.png)

Make sure that your items have correct fields values.
![image](https://cloud.githubusercontent.com/assets/6848691/24830993/0f065ffe-1c91-11e7-826e-cf71a34ab2a4.png)


### Summary
We left some items unbucketable under blog root, but not blog posts.

In case of any problems with default field values, you can create a new blog using one of the branches (web forms, MVC) and compare side by side and alter your items if needed. 

**If you spot new issue, please create a separate ticket.**

**Comment by gadgetman110** [comment]
Thank you for the response.  Unfortunately (although I'm going to try your suggestions on my local, dev instance) we cannot change our blogs to buckets at this time in production as there are quite a lot and this would change the url's.

We HAVE managed to find a way to reproduce the issue though!

We have a lot of blogs on the blog listing page and have several different language versions.  If you Create a blog and in English Australia version, change the work flow to approved and publish it (JUST FOR EN-AU) and then pull up the blog listing page and all the blogs are gone.

To get them back you can flip layouts, or delete the recently created en-au blog, recreate it and the publish with (for instance) EN-AU and EN-GB.

**Comment by gadgetman110** [comment]
At first we suspected the index getting corrupted, however, we can do a WeBlog reindex right after this issue occurs and it does not help.

**Comment by adeneys** [comment]
How do you rebuild the WeBlog index? Do you use the utility in the control panel? This utility is for the older Sitecore Lucene search which was used before Content Search. This would be there if you upgraded from an older WeBlog version but won't rebuild the content search index used by WeBlog.

**Comment by gadgetman110** [comment]
Hello.  Yes, that is exactly how we reindex it.  We used the utility.  So how should we do this and if this is the issue, how did the index get corrupt?


Thanks!


________________________________

**Comment by adeneys** [comment]
WeBlog now only uses Content Search, so use the indexing manager to rebuild the WeBlog indexes. I'm not sure how the indexes would become corrupt. It may be a race condition between indexing and caching.

**Comment by gadgetman110** [comment]
We had a session with Sitecore yesterday and they definitely pointed the finger at the issue being with WeBlog.  Is there anything you guys can do to help?


________________________________

**Comment by adeneys** [comment]
As I mentioned, I suspect this is the classic race condition between rendering caching and indexing that we often saw in older versions of Sitecore and WeBlog. Especially if you updated from an older version (which you did), then the configuration might not be updated to counter this issue.

Disable all caching as Alan suggested above, then rebuild the WeBlog indexes using the Indexing Manager (Control Panel > Indexing Manager). For your live website, rebuild the WeBlog_web index. If that works, then it indicates some misconfiguration of your blog, which is likely given it was from an upgrade of an older version.

It would probably also help it you created a new blog using one of the blog branches so you can prove it can work and to inspect the settings.
