### ISSUE TITLE
broken links in Sites Running on WeBlog

### ISSUE THREAD

**Issue by DLN-India** [WeTeam/WeBlog#243]
http://blog.redarrowsoftware.com/ seems broken

**Comment by DLN-India** [comment]
https://www.magenium.com/techblog has to be updated to 
https://www.magenium.com/Information/Articles

Although its uncertain whether they're still running sitecore

**Comment by alan-null** [comment]
@DLN-India Thank you for reporting. I will review the rest and remove obsolete links.
