### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by Wobin** [WeTeam/WeBlog#244]
I've just recently ported a Weblog from 7.2 to 8.2 and one thing I've noted is that entry dates are saved as UTC, and then rendered without a timezone applied. I'm unsure if this is a setting I'll have to adjust in Sitecore generally, or something specific to Weblog.

EG: an entry saved as 12am 1st Feb 2017 (AEST), is being stored as 1pm 31st Jan 2017. Then rendered on page as being in January (and sorted similarly)

**Comment by adeneys** [comment]
Sitecore 8 started storing date fields as UTC. So the proper fix here would be to convert all your date field values over to UTC to correct the issue.

**Comment by alan-null** [comment]
This might be helpful: [Sitecore 8 ServerTimeZone – my dates are all wrong](https://briancaos.wordpress.com/2015/04/16/sitecore-8-servertimezone-my-dates-are-all-wrong/)
