### ISSUE TITLE
Bucket revert issue

### ISSUE THREAD

**Issue by nagireddyt** [WeTeam/WeBlog#247]
Hi,

While upgrading Sitecore project from 7.2 to 8.2 version, having an issue after upgrading weblog module. For any Bucket items in the project,  if I click on Revert all the bucketable items are deleting instead of showing content tree structure and those items are deleted permanently. 
Raised a Sitecore support ticket for the same, Sitecore team verified and said this issue is caused by weblog module code, updated Sitecore comments below. So can you please help us in fixing this issues.

-----------------Sitecore support comments -------------
During the investigation of your configuration, I found that you use WeBlog shared module which can influence the bucket process. And after installing WeBlog module I was able to reproduce the behavior described by you ( mentioned above).
It looks like the problem occurred during the item:saved event in <handler type="Sitecore.Modules.WeBlog.EventHandlers.SyncBucket, Sitecore.Modules.WeBlog" method="OnItemSaved" /> handler.
To prevent deleting the items after bucket revert please comment out this handler. For example, by disabling the WeBlog.config files.
---------------------------------------------------------------

**Comment by alan-null** [comment]
Hi @nagireddyt 

Could you please provide detailed steps to reproduce the issue?

**Comment by nagireddyt** [comment]
Thanks Alan, for a quick response.

I created a sample to reproduce the issue.
[BucketRevertIssue.zip](https://github.com/WeTeam/WeBlog/files/1069405/BucketRevertIssue.zip)
Install attached package in  Sitecore 8.2 - Update 2 version. It will create below-mentioned items
1. Under Sitecore/Templates -it will Create PlansBucket & PlansBucketable templates
2. Under Sitecore/Content -PlansBuck/PlansBucketable1 items will be created.

Now Navigate to sitecore/Content/**PlansBuck** -> In ribbon goto Configure tab -> Click on 'Revert' ->  bucketable item 'PlansBucketable1' will be deleting instead of showing in content tree structure.

Please let me know if you need more details.

**Comment by alan-null** [comment]
Hey @nagireddyt 

Please find attached file
[Sitecore.Modules.WeBlog.Support247-1.0.zip](https://github.com/WeTeam/WeBlog/files/1069663/Sitecore.Modules.WeBlog.Support247-1.0.zip)

This is standard Sitecore package. It contains following files inside:
- `files\App_Config\Include\WeBlog.Support247.config`
- `files\bin\Sitecore.Modules.WeBlog.Support247.dll`

Once you install it your problem should be gone.

**Comment by nagireddyt** [comment]
Thank you very much Alan :) it worked

**Comment by nagireddyt** [comment]
Hi Alan,

We got another issue after including this fix files.
[Blog_Issue.zip](https://github.com/WeTeam/WeBlog/files/1110386/Blog_Issue.zip)

Install attached package in sitecore 8.2 and update 'Entry Date' field under /sitecore/content/New Folder/2017/April/New Entry date to June (For ex : 28-April-2017 to 21-June-2017 ) then new folder with name 'June' will be created in the existing Weblog code, but after updating with Weblog fix its not creating new folder. Can you please help us in fixing the issue.

Thanks in advance.

**Comment by alan-null** [comment]
Following Sitecore version fixes all the problems.
**Sitecore.NET 8.2 (rev. 170728)
rev. date July 28, 2017**

I verified both packages using mentioned Sitecore version and the latest WeBlog release and everything work fine.
