### ISSUE TITLE
3.1.0 Custom Templates and Weblog.Custom.config

### ISSUE THREAD

**Issue by ufpian** [WeTeam/WeBlog#248]
Having recently updated to 3.1.0, we've found our custom configuration breaks aspects of our sites, such as properly inserting new entries based on custom templates.  Could you provide an updated custom config to allow the usage of these templates, or advise on how to incorporate these custom templates back into our sites?

**Comment by adeneys** [comment]
Could you please clarify your issue a little more? Is the issue that you're trying to use custom templates instead of the normal WeBlog templates, and after the upgrade your custom templates are no longer being used, the normal WeBlog templates are being used again?

**Comment by ufpian** [comment]
I apologize that this has taken me so long to get back to.  I believe this was a setup issue on our end, and has since been resolved.  Thanks for your time.

**Comment by adeneys** [comment]
Thanks for letting me know @ufpian
