### ISSUE TITLE
WeBlog - fallback language

### ISSUE THREAD

**Issue by cv1998** [WeTeam/WeBlog#252]
Hi,
We are using Sitecore 8.1 rev. 160519 and WeBlog-3.1.0_sc8.0-8.1.zip

we have en-US language and the fallback language is en

The content is in en language
the web site use en-US language (so the url is /en-US/xxx)

We create a blogen in en language.

Looks like the blog index page with en-US (/en-US/test/blog/blogen/) is not working (missing list of entry, archive, etc.) (please see the screenshot weblog.docx)

the entry detail page with en-US (/en-US/test/blog/blogen/2017/august/entry1/) is missing archive, etc.

Am i missing something?

Thanks

[weblog.docx](https://github.com/WeTeam/WeBlog/files/1208903/weblog.docx)

**Comment by adeneys** [comment]
Hi @cv1998 
This is not a supported configuration for WeBlog currently. WeBlog uses the language of the `Context.Item` item to perform the search for the items used to populate those controls.
