### ISSUE TITLE
Creating blog entry causes error 500

### ISSUE THREAD

**Issue by andyram2k** [WeTeam/WeBlog#256]
Hi,

I've installed the package from: WeBlog-3.1.0_sc8.0-8.1.zip, onto my local development Sitecore 8.1 instance to expand and re-style.

The package has installed everything correctly as far as i can tell. I've published and built both indexes too. The issue comes when i click on the blog parent and then create "Entry" - it hangs and then causes error 500 and slows the instance down. 

The "Loading facets" also is slow to load when looking for:
_templatename: blogentry, _templatename: blogcomment and sort: created date.

UPDATE: I've tracked this down to:

**App_Config/Include/Weblog.config - Line 15** 
<handler type="Sitecore.Modules.WeBlog.EventHandlers.SyncBucket, Sitecore.Modules.WeBlog" method="OnItemSaved" /> causing all buckets to not allow item creation, just error 500:

Error:

System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Sitecore.Data.Database.CreateItemPath(String path, TemplateItem folderTemplate, TemplateItem itemTemplate)
   at Sitecore.Buckets.Managers.BucketProvider.CreateAndReturnBucketFolderDestination(Item topParent, DateTime childItemCreationDateTime, ID itemToMove, String itemName, ID templateId)
   at Sitecore.Buckets.Commands.AddFromTemplateCommand.DoExecute()
   at Sitecore.Data.Engines.EngineCommand`2.Execute()
   at Sitecore.Data.Managers.ItemProvider.AddFromTemplate(String itemName, ID templateId, Item destination, ID newId)
   at Sitecore.Data.Managers.PipelineBasedItemProvider.<>c__DisplayClass3.<AddFromTemplate>b__2()
   at Sitecore.Data.Managers.PipelineBasedItemProvider.ExecuteAndReturnResult[TArgs,TResult](String pipelineName, String pipelineDomain, Func`1 pipelineArgsCreator, Func`1 fallbackResult)
   at Sitecore.Data.Managers.ItemManager.AddFromTemplate(String itemName, ID templateId, Item destination, ID newItemId)
   at Sitecore.Data.Managers.ItemManager.AddFromTemplate(String itemName, ID templateId, Item destination)
   at Sitecore.Data.Items.Item.Add(String name, TemplateID templateID)
   at Sitecore.Workflows.WorkflowContext.AddItem(String name, TemplateItem template, Item parent)
   at Sitecore.Shell.Framework.Commands.AddMaster.Add(ClientPipelineArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Sitecore.Reflection.ReflectionUtil.InvokeMethod(MethodInfo method, Object[] parameters, Object obj)
   at Sitecore.Nexus.Pipelines.NexusPipelineApi.Resume(PipelineArgs args, Pipeline pipeline)
   at Sitecore.Web.UI.Sheer.ClientPage.ResumePipeline()
   at Sitecore.Web.UI.Sheer.ClientPage.OnPreRender(EventArgs e)
   at Sitecore.Shell.Applications.ContentManager.ContentEditorPage.OnPreRender(EventArgs e)
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Thanks,

Andy

**Comment by adeneys** [comment]
Thanks for the info @andyram2k . Which revision of Sitecore are you using? I tested this on Sitecore 8.1 prior to release, without any issue (though I can't find which revision it was now; different computer which has since crashed).

Also, how have you determined the WeBlog event handler is causing the issue? I don't see any mention of a WeBlog namespace in the stack trace above. There's a possibility that other bucket settings are affecting this process, such as the `DynamicBucketFolderPathSelector` further down the config file (about line 183).

**Comment by andyram2k** [comment]
Hi @adeneys, we're using Sitecore.NET 8.1 (rev. 151003). Through trial and error, i narrowed it down to this line in the config, and when removed, it stopped the bucket slow loading and allowed me to create a new bucket item without error. It could indeed be the DynamicBucketFolderPathSelector that is the issue.

Following on from first logging this issue and commenting out the line, i've managed to create blog items and got the blog working to an extent, but when you click on the blog "parent" page, it's still very slow to load and struggles to load facets for the 3 items, so there is an underlying issue. I tried installing the same package on another dev server (same version), it still hangs and can stop the creation of bucket items through error 500,  even on buckets outside of the blog too.

Other issues i've found also (Using MVC) after installing the package:

1) When loading a blog entry page, i get:
System.InvalidOperationException: Error while rendering view: '/Views/WeBlog/EntryTags.cshtml'.
 ---> System.MissingMethodException: Method not found: 'Boolean PageMode.get_IsExperienceEditorEditing()'. - I can't seem to find this anywhere to remove it. 

2) In view renderings, i've had to replace all references of "Model.IsPageEditing" to be "Sitecore.Context.PageMode.IsPageEditor", to stop rendering errors.

3) Again when loading a blog entry page, i get an error relating to recaptcha, but this is already installed with this version:
"Could not load file or assembly 'Recaptcha, Version=1.0.5.0, Culture=neutral, PublicKeyToken=9afc4d65b28c38c2' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)". I haven't been able to test the submitting of comments out, due to the above.

Any help would be greatly appreciated to solve these issues, as it's not far off, it'll be a few tiny things stopping the whole thing from working. Happy to test as many times as necessary.

Andy

**Comment by adeneys** [comment]
That first supplemental issue you mention sounds very odd. The Experience Editor was introduced in Sitecore 8.0 to replace the Page Editor from previous versions. This property (`Context.PageMode.IsExperienceEditorEditing`) exists in the kernel, so if you're getting errors that the property cannot be found, then your installation might not be the version you expect.

The second supplemental point is a symptom of the first issue. If the first issue was resolved, you won't need to change from `Model.IsPageEditing`.

For the third point, can you validate the exact assembly version? You'll need a reflection tool like (ILSpy)[http://ilspy.net/] to get the exact version.

Which search provider are you using for content search? I'll need to set this up again locally to test your initial issues with the buckets and facet loading.

**Comment by andyram2k** [comment]
I've downloaded the ILSpy and viewed the SitecoreKernel.dll file and it contains the following:

[assembly: AssemblyVersion("8.1.0.0")]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: AssemblyCompany("Sitecore Corporation")]
[assembly: AssemblyCopyright("© 1999 - 2015. All rights reserved. Sitecore is a registered trademark of Sitecore Corporation A/S.")]
[assembly: AssemblyDescription("Sitecore CMS Kernel Library.")]
[assembly: AssemblyFileVersion("8.1.0.5297")]
[assembly: AssemblyInformationalVersion("8.1.0 rev. 151003")]
[assembly: AssemblyProduct("Sitecore CMS")]
[assembly: AssemblyTitle("Sitecore.Kernel")]

We're using Lucene search primarily. 

I'll keep investigating and let you know if i manage to resolve any of this.

Andy

**Comment by andyram2k** [comment]
Hi @adeneys,
I'm hoping to have a trial working blog ready for the end of September. Do you think you may have any fixes for this time please? It's a great product and i really want to make it look as good as it can be, i just need the few issues working out to make it usable, especially when putting onto the live servers.

Thanks again, i really appreciate it.

Andy

**Comment by adeneys** [comment]
Hi @andyram2k,
Looks like the `Method not found: 'Boolean PageMode.get_IsExperienceEditorEditing()'.` issue is related to that exact version of Sitecore 8.1. I setup both the 8.1 initial release (rev 151003) and update 3 (rev 160519) locally. On rev 151003 I also saw the same error you mentioned when viewing the entry page. However, this issue did not appear on rev 160519, so the APIs between these versions must be different.

I also tried doing a quick build of the solution against each of these versions and faced issues, so obviously the API difference between Sitecore 8.0 and 8.1 was more significant than we assumed.

I'll need to add a new build target for Sitecore 8.1 and create a new package, but I can't commit to any specific dates.

BTW, I didn't experience the bucket issue you originally reported for either of these Sitecore versions. In both cases I was able to create new blog entries without issue. The fact you have issues loading the facets indicates there may be an underlying issue in your Sitecore instance and search index.

**Comment by andyram2k** [comment]
Hi @adeneys, thank you - i appreciate everything you're doing.

I've amended the templates to work with our current setup, so the basics of the blog are now showing. Will look into the search issue and when i find out what might be causing it, will report back.

Best regards,

Andy

**Comment by andyram2k** [comment]
Hi @adeneys, do you think you'll be able to create the fixes soon please?

I've tried building the github files against our sitecore version mvc instance to try and update dll files, but ended up with quite a few errors when building, such as sitecore.data not being found, for example. Whether I'm not doing this right, I'm not sure. 

As I mentioned, I've got the majority of functionality working, I think the main errors are the experienceeditor boolean error, mentioned previously that stops the preassigned elements from working or displaying the page, unless they are removed.

The only other thing I couldn't quite get working, is if I wanted to search by author, I thought it would be a case of adding a new lucene field of author in the same file as date and tags, but when i try this in the URL /?author=test, this doesn't work. Does this need to be compiled into a dll too?

I think the difficulty I'm facing is that there's quite a few parts within the dlls which I'm not currently able to update.

Any help would be appreciated, as id like to get a working blog sorted as soon as is possible.

Thanks again for your time.

Andy

**Comment by andyram2k** [comment]
Hi @adeneys ,

I've made quite a bit of progress with getting the blog working with our 8.1 Sitecore:

1) I've removed the interesting entries, as this causes an error due to the incorrect isediting boolean, and from what i can tell, Sitecore is planning on replacing Mongo with SQL in Azure in V9.
2) I've amended the boolean in .cshtml files to be "Sitecore.Context.PageMode.IsPageEditorEditing" instead
3) I've found the thing that was causing content editor to hang when you click on the bucket - it's the "custom:_templatename|blogentry;custom:_templatename|blogcomment;sort:created date" facet syntax that slowed it down when you clicked on the bucket. When it's removed, it creates new entries without issue. Not sure if this means we have an issue with Lucene or not.

Now the blog seems to work, including commenting after adding recaptcha again from nuget. The only issue i have now is with wordpress import, but i'll include this on a separate issue.

If you could let me know when an 8.1 version is made, i would really appreciate it.

Thanks again,

Andy

**Comment by andyram2k** [comment]
Hi @adeneys,

I've managed to build against our version of sitecore, so can now make amends to replace the boolean. Will report back with any other 8.1 specifics that I come across.

Many thanks,

Andy
