### ISSUE TITLE
Is subcategory supported in Sitecore after importing from wordpress xml file?

### ISSUE THREAD

**Issue by mukeshnikhil2000** [WeTeam/WeBlog#257]
Hi,

Wordpress blog is having category and subcategory and once we export, the exported xml file has child parent relationship. Once it is imported in Sitecore 8.2(from Weblog 3.1), blog is created and working fine.
But I can't see subcategories or any relationship between child and parent categories and also don't see any option to search by subcategory. 
Has it been taken care of in Weblog or am I missing something?

**Comment by alan-null** [comment]
Hey @mukeshnikhil2000 

Subcategories are not supported: https://github.com/WeTeam/WeBlog/issues/50.
WeBlog does not provide an ability to manage subcategories.

WeBlog flattens categories during import.
It does not rely on the category structure but what is assigned to a post (category name), after importer gets a category name it tries to create a new category or get existing, so information about subcategories is lost.
