### ISSUE TITLE
Tags (Multi Word) not working in Solr but working in Lucene

### ISSUE THREAD

**Issue by teggis** [WeTeam/WeBlog#258]
Is anyone have the issue with the tag cloud not returning posts when there is a multiple word tag? It works in Lucene just fine but with Solr it does not work. Example is: "working today". With Solr click on "working today" returns nothing but Lucene brings backs post's with this tag. In Solr if you search by one or the other word's "working" or "today" it returns posts. Any help will be appreciated.

**Comment by alan-null** [comment]
Hey @teggis 
Solr support is on our to-do list: #172

**Comment by SomnathD** [comment]
Hi There,

I have the same problem after migrating my project to Sitecore 9 and Solr 6.6.3.
Is there an update if this is still a work in progress or if there is a specific version of the module available that can help?

Thanks in advance.

Regards
Somnath

**Comment by adeneys** [comment]
Closing this issue as Solr support is currently being worked on in issue #172
