### ISSUE TITLE
archive months as pages with lists of posts made in that month

### ISSUE THREAD

**Issue by andyram2k** [WeTeam/WeBlog#264]
Hi,

I've been looking at some of the example sites using weblog, and a few of them have their archive months as pages, that when you click on them then display entries from that month.

Is this included in weblog and I've missed a setting or is there a simple way to create this from bucket folder items?

Thanks,

Andy

**Comment by alan-null** [comment]
Hi @andyram2k 

You are right, some sites have that feature but it doesn't look like they are running WeBlog
List of sites might be outdated as we do not update it actively.

API is able to return items by month and year
https://github.com/WeTeam/WeBlog/blob/master/src/Sitecore.Modules.WeBlog/Managers/EntryManager.cs#L240
but current implementation of `PostList ` is unable to display items in a way you want.

**Comment by andyram2k** [comment]
Hi Alan,

Do you know how they've been able to treat bucket folders as pages? Or do you think they've created them as pages?

Thanks,

Andy

**Comment by alan-null** [comment]
We don't know what they have in their database, if they are not using WeBlog it can be a normal page.
By the way, I've never tried that but you could assign a layout to a bucket grouping item and see what will happen.

In the past, we were using NewsMover in WeBlog to manage year/month folder structure. Back then it was easier to change configuration and change the type of folder so you could use your own folder with layout and place rendering which would render your desired content.

Even though you will be able to treat folders as pages you need to take care for auto layout assignment plus create or extend PostList rendering.

**Comment by andyram2k** [comment]
Hi Alan,

In the current api, is it possible to do text search on blog entries for the current blog you're in? Also, is it possible to get the number of entries in a category to display next to this? I could add these as separate issues if needed, but didn't want to fill up an issue log with just questions.

Thanks,

Andy

**Comment by alan-null** [comment]
1. Search - not implemented yet
#10 Blog Search

2. Categories - case not supported with the current implementation
