### ISSUE TITLE
Category creation issue

### ISSUE THREAD

**Issue by dbibby** [WeTeam/WeBlog#266]
We are in the process of updating our Sitecore version to version 8.2
I am assigned the task of updating our current WeBlog (WeBlog-2.4.0) installation to run with Sitecore version 8.2. I have installed WeBlog-3.1.0.
Using the Sample blog, when trying to create a new category in the categories folder, the new category is created outside of the selected folder in the root of the blog.
Am I missing a configuration or something?

**Comment by dbibby** [comment]
Update to the previous post.  So when creating a new category the steps were as follows:
- Select the Categories folder
- Right mouse
- Select insert from Category insert option
- Name the Category and the new category is created outside of the Categories folder.
I have just tried another way to create a category by selecting "Insert from template" and choosing the category (Webforms) template.  This method results in the category being created inside the Categories folder.  So, it looks like the problem is with the Category insert option.

**Comment by adeneys** [comment]
That sounds about right. WeBlog 3.0 introduced full MVC support, so we had to use different templates for WebForms and for MVC, to get the presentation right. When you created the sample blog, did you use the appropriate blog branch (Branches > Modules > Blog WebForms)? This branch is setup with all the correct templates and insert options.

**Comment by alan-null** [comment]
Closed due to lack of activity.
