### ISSUE TITLE
The wiki document file is out dated since version 2.4

### ISSUE THREAD

**Issue by ppabon57** [WeTeam/WeBlog#267]
I'm working on setting up a site using the 3.1 module but would like to have an updated documentation with your latest version 3.1, is this possible?

**Comment by adeneys** [comment]
I agree, the wiki is in need of revision. Have you found any articles in particular which appear to no longer be valid?

**Comment by ppabon57** [comment]
Hi Alistair,

The steps for creating the blog was one but also the versions on the marketplace was outdated from what’s on Github but I managed to get what needed from GitHub however my plan was to use version 3.1 has this been QA is it stable enough for production use?


Sent from my iPhone

On Jan 28, 2018, at 4:09 PM, Alistair Deneys <notifications@github.com<mailto:notifications@github.com>> wrote:


I agree, the wiki is in need of revision. Have you found any articles in particular which appear to no longer be valid?

**Comment by adeneys** [comment]
Yes, version 3.1 has been tested and is expected to be production ready. Though keep in mind, this is an open source project and you use it at your own risk :).

Thanks for providing the above page and info on the Marketplace. I'll look to get those updated.

**Comment by ppabon57** [comment]
Hey Alistair,

Just to confirm this module will run with SC 8.1 Update 1 right?
because I didn't see that option on the config settings

**Comment by adeneys** [comment]
Yes, it will run on Sitecore 8.1 update 1. Historically we've tried to keep the number of build configurations as low as possible. For 8.1 you should be able to use the sc8.0 config. Let me know if you run into any specific issues.

**Comment by adeneys** [comment]
FYI, I just updated the blog creation wiki page: https://github.com/WeTeam/WeBlog/wiki/Create-and-setup-blog
