### ISSUE TITLE
Inherited build config setting issues

### ISSUE THREAD

**Issue by ppabon57** [WeTeam/WeBlog#268]
The inherited build configurations doesn't apply the settings properly, the target frame work 4.5.2 just gets defaulted to 4.5, it would work fine if the condition was an equal to "Debug sc8.2" instead of using Contains, but then you would have to place the DEBUG;TRACE; constants within the same config setting

&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003"&gt;
	&lt;PropertyGroup Condition="$(Configuration.Contains('Debug'))"&gt;
		&lt;DefineConstants&gt;$(DefineConstants);DEBUG;TRACE&lt;/DefineConstants&gt;
	&lt;/PropertyGroup&gt;
        ......
	&lt;PropertyGroup Condition="$(Configuration.Contains('sc8.2'))"&gt;
		&lt;TargetFrameworkVersion&gt;v4.5.2&lt;/TargetFrameworkVersion&gt;
                
&lt;DefineConstants&gt;$(DefineConstants);FEATURE_XDB;FEATURE_EXPERIENCE_EDITOR;FEATURE_UTC_DATE;FEATURE_SERVICES_CLIENT&lt;/DefineConstants&gt;
		&lt;OutputPath&gt;bin\sc82\&lt;/OutputPath&gt;
	&lt;/PropertyGroup&gt;
&lt;/Project&gt;

**Comment by ppabon57** [comment]
Alistair,

I noticed you have a lot of transformation files using xslt.....
If I needed to for example use the WeBlog.config
would I need to just rename the WeBlog.config.delivery.xslt to WeBlog.config.xslt ?

**Comment by adeneys** [comment]
I haven't had any issue with the `Contains` condition in MSBuild, but VS might not report the settings properly. Make sure you've got MSBuild verbosity set to at least "Normal" and check your build output. When I select build config `Debug sc8.2` I can see the target framework is 4.5.2.

The XSLTs are used to generate variations of the config for various targets, such as specific Sitecore versions, or for a particular Sitecore deployment role. If you're making adjustments to the config, just make them in the `WeBlog.config` file. To generate the additional files, just build the project. We use the `AfterBuild` target to run the transforms.

**Comment by ppabon57** [comment]
Interesting....

Would these build target settings work if this was automated in VSTS?

Sent from my iPhone

On Feb 5, 2018, at 11:55 PM, Alistair Deneys <notifications@github.com<mailto:notifications@github.com>> wrote:


I haven't had any issue with the Contains condition in MSBuild, but VS might not report the settings properly. Make sure you've got MSBuild verbosity set to at least "Normal" and check your build output. When I select build config Debug sc8.2 I can see the target framework is 4.5.2.

The XSLTs are used to generate variations of the config for various targets, such as specific Sitecore versions, or for a particular Sitecore deployment role. If you're making adjustments to the config, just make them in the WeBlog.config file. To generate the additional files, just build the project. We use the AfterBuild target to run the transforms.

**Comment by adeneys** [comment]
Should do. VSTS just runs MSBuild, so there shouldn't be any issue.
