### ISSUE TITLE
Archive setup - EntryList issue

### ISSUE THREAD

**Issue by chipsterva** [WeTeam/WeBlog#273]
Good day, @adeneys  - here is my followup question.  We would like to change the default archive functionality a bit; instead of listing the entries in the sidecar archive component, we would like instead to show the months (number) as a link to a landing page that then shows the entries for that year/month.  I have accomplished most of what we want to do by using querystrings and updating the URLs in the pertinent places, and it functions after a fashion.  The key piece of this working is that I have updated the PostList.cshtml page with the following code:

```
@using Sitecore.Modules.WeBlog.Globalization
@using Sitecore.Modules.WeBlog.Mvc.Model
@using System.Globalization
@model Sitecore.Modules.WeBlog.Mvc.Model.PostList

<div class="wb-entry-list"> 
    @if (HttpContext.Current.Request.QueryString["archive"] == "1" && HttpContext.Current.Request.QueryString["month"] != "")
    {
        var monthName = @DateTimeFormatInfo.CurrentInfo.GetMonthName(Convert.ToInt32(@HttpContext.Current.Request.QueryString["month"]));
        <h1>@monthName @HttpContext.Current.Request.QueryString["year"] Archives</h1>
        foreach (var entry in Model.Entries.Where(x => x.EntryDate.DateTime.Year.ToString() == HttpContext.Current.Request.QueryString["year"] && x.EntryDate.DateTime.Month.ToString() == HttpContext.Current.Request.QueryString["month"]))

        {
            Html.RenderPartial(Model.PostTemplate, new BlogAuthors(entry));
        }
    }
    else
    {
        foreach (var entry in Model.Entries)
        {
            Html.RenderPartial(Model.PostTemplate, new BlogAuthors(entry));
        }
    }

@if (HttpContext.Current.Request.QueryString["archive"] != "1")
    {
        if (Model.ShowViewMoreLink)
        {
            <div class="wb-view-more-wrapper">
                <a id="ancViewMore" class="btnWrapper" href="@Model.ViewMoreHref&rtb=1">
                    <span class="btn">@Translator.Render("VIEW_MORE").ToHtmlString()</span>
                </a>
                <span class="wb-loading-animation" style="display: none;">Loading...</span>
            </div>
            }
    }
</div>
```
The URL that calls this looks something like this:  http://www.company.site/hda-blog?rtb=1&archive=1&month=10&year=2018

RTB is a value for return to blog, a display component with a link back to the top of the blog; Archive is a flag for PostList to either show the archive list or, if 0, show default list; Month and Year feed the delimiters on the Model.Entries.Where code.

The problem I have run into with this configuration is that the blog DisplayItemCount appears to affect the number of entries pulled into the PostList.Entries class, and it affects whether or not entries will show on the archive page.  If I have set the blog's DisplayItemCount higher than the number of entries in the blog, everything works fine.  When that number is less than the number of total entries. squirrely things happen - blog entries are not show, and it appears only the number of entries available matches the number in DisplayItemCount.

I saw that Categories does not suffer from this ailment, so I have tried to parse through how the Entries list is constructed and shaped for it.  So far, I have not had any success getting Archives to work similarly.  I have tried creating a new template based on categories and moved it out of the Categories folder, but no entries are shown.  I have tried creating a new page item, changing the template to either blog or category, and update accordingly, but it also returns empty.

Other than adding some kind of jquery accordion function on top of the existing WeBlog code, is there a better way to tackle this?  It seems it should be ideal to mimic how categories works, but not sure how to get that to happen.

Thanks again!  I promise this will be a shorter back and forth!

**Comment by adeneys** [comment]
Hi @chipsterva ,
To make this scenario work you need the `PostList` model class to provide all the entries you need. Ideally, you'd move that filtering logic out of your view and into the model, so the entries which are available via the `Entries` property can be rendered in full, in the same fashion as a normal listing page.

The `Entries` property is populated inside the `PostList` class by using an instance of `IPostListCore`. The default implementation is provided by the `PostListCore` class. Take a poke around this class and you'll find exactly how the entries are found, and you'll also find the page filtering logic in it's `Entries` property. That class uses the `count` query string to determine how many items to return. If you wanted something quick and dirty, you could add a high count into the query string. Though this may suffer from performance issues if you have a higher number of blog entries.

A better solution would be to subclass `PostListCore` and add in additional logic for pulling out the correct entries from the `EntryManager`, which includes a parameter on the `GetBlogEntries()` method which accepts start and end dates for filtering. Overload the `GetEntries()` method and check your query string parameters in there. If you don't have the parameters for your logic, use the base class implementation.

    public class CustomPostListCore : PostListCore
    {
        protected overload IEnumerable<EntryItem> GetEntries()
        {
            var year = QueryString("year");
            var month = QueryString("month");

            if(... // year and month are populated)
            {
                // parse year and month to create start date and end date
                entries = ManagerFactory.EntryManagerInstance.GetBlogEntries(CurrentBlog, int.MaxValue, tag, null, startDate, endDate);
            }
            else
            {
                return base.GetEntries();
            }
        }
    }

This is more efficient than pulling back all entries and filtering those. It would also support paging through the monthly blog posts, which would be handy if you had a high number of posts.

If you subclass `PostListCore` you'll also need to subclass the `PostList` model class so you can specify your custom `IPostListCore` implementation:

    public class CustomPostList : PostList
    {
        public CustomPostList() : base(new CustomPostListCore(CurrentBlog))
        {
        }
    }

And of course update your view to use your custom `PostList` model as the model.

**Comment by chipsterva** [comment]
Thanks for all of the info and code, @adeneys.  I was finally able to devote some time to this yesterday and today.  I have most of the code worked out, but I have an error that comes up in the VS editor that I can't figure out.

My code looks like this:

```
namespace Sitecore.Modules.WeBlog.Components
{
    public class CustomPostListCore : PostListCore, ICustomPostListCore
    {
        protected override IEnumerable<EntryItem> GetEntries()
        {
            var year = HttpContext.Current.Request.QueryString["year"];
            var month = HttpContext.Current.Request.QueryString["month"];

            if (!string.IsNullOrEmpty(year) || !string.IsNullOrEmpty(month))
            {
                int yr = 0;
                int mnth = 0;
                Int32.TryParse(HttpContext.Current.Request.QueryString["year"], out yr);
                Int32.TryParse(HttpContext.Current.Request.QueryString["month"], out mnth);
                var startDate = new DateTime(yr, mnth, 1);
                var endDate = startDate.AddMonths(1).AddDays(-1);
                entries = ManagerFactory.EntryManagerInstance.GetBlogEntries(CurrentBlog, int.MaxValue, null, null, startDate, endDate);
            }
            else
            {
                return base.GetEntries();
            }
            return entries;
        }
    }

    public interface ICustomPostListCore : IPostListCore
    {
    }
}
```

```
namespace Sitecore.Modules.WeBlog.Mvc.Model
{
    public class CustomPostList : PostList
    {
        public CustomPostList() : base(new CustomPostListCore(CurrentBlog))
        {
        }
    }
}
```

PostListArchive.cshtml
```
@model Sitecore.Modules.WeBlog.Mvc.Model.CustomPostList

<div class="wb-entry-list">

    @foreach (var entry in Model.Entries)
    {
        Html.RenderPartial(Model.PostTemplate, new BlogAuthors(entry));
    }
    @if (Model.ShowViewMoreLink)
    {
        <div class="wb-view-more-wrapper">
            <a id="ancViewMore" class="wb-view-more" href="@Model.ViewMoreHref">
                @Translator.Render("VIEW_MORE").ToHtmlString()
            </a>
            <span class="wb-loading-animation" style="display: none;">Loading...</span>
        </div>
    }
</div>
```
I see the following message in VS for the code 
`public class CustomPostListCore : PostListCore, ICustomPostListCore`
Base class Sitecore.Modules.WeBlog.Components.PostListCore does not contain parameterless constructor.

I also see a message in VS for the code
`public CustomPostList() : base(new CustomPostListCore(CurrentBlog))`
An object reference is required for the non-static field, method or property BlogRenderingModelBase.CurrentBlog.

I figure the two issues are related, and I am guessing the real problem is with the second one, regarding CurrentBlog.  In comparing the original code and my modified code, though, I am not sure why this is.  Isn't the value for CurrentBlog being inherited via PostList and PostListCore?

Thanks again for everything -

**Comment by adeneys** [comment]
The first error is saying that `PostListCore`, which you inherit from in `CustomPostListCore`, doesn't have a constructor with no parameters, so you need to add a constructor to `CustomPostListCore` and call the constructor of the base class.

    public class CustomPostListCore
    {
        public CustomPostListCore(BlogHomeItem currentBlog)
            : base(currentBlog, null, null)
    }

You can also add the additional parameters (`IWeBlogSettings, IAuthorsCore`) to the constructor if you'd like, if you plan on using them.

The error message about the use of `CurrentBlog` is because in the call to the base constructor, you don't yet have a class instance, so you can't access any instance members, and `CurrentBlog` is an instance property. Instead, Do as `PostList` does and set the `PostListCore` property inside the constructor body:

    public CustomPostList()
    {
        PostListCore = new CustomPostListCore(CurrentBlog);
    }

**Comment by chipsterva** [comment]
That did the trick, @adeneys!  I need to clean out the work I did previously on archiving and replace it with the archive page, but it appears to be pulling the expected number of entry items and rolling over content as expected.  Thanks again for everything!

I will let you know when we have the blog published and publicly available.  It can be added to the list of user sites at that point.  Thanks~

**Comment by chipsterva** [comment]
Thanks again for everything, @adeneys!
