### ISSUE TITLE
Sitecore 9 compatible version

### ISSUE THREAD

**Issue by pvaartstra** [WeTeam/WeBlog#278]
Need a version that will run on Sitecore 9.0

**Comment by adeneys** [comment]
We have Sitecore 9.0 support on the `develop` branch already (https://github.com/WeTeam/WeBlog/tree/develop). We're in the midst of development for the next release at the moment which will include that, as well as support for Sitecore 9.1.

**Comment by olegbabkevich** [comment]
Hello,
Could you say if there are timelines when it possibly be released?

**Comment by adeneys** [comment]
Sorry @olegbabkevich, no ETA. It's being actively worked on at the moment. As mentioned above, 9.0 support is already available on the develop branch, and 9.1 support has been added as well.

**Comment by basselissa** [comment]
Hello, is there any 9.0 and 9.1 package to download, as packaging is not clearly documented.

**Comment by djanjicek** [comment]
Yes indeed, it would be great if you could provide upgrade packages or better instructions.

**Comment by solkararif** [comment]
hello,
support for 9.2 has been added as to this release? Where can I get a clear instruction to package and deploy the commit to test locally.

**Comment by adeneys** [comment]
Hi @solkararif,
The release has not been made yet. I'm still working through testing and validation. If you want to try it yourself locally before the release is complete, checkout the `feature/9.2-9.3-support` branch and follow the instructions in the `how to build.md` file in the root of the repo.

**Comment by solkararif** [comment]
Hi @adeneys .
I have followed the instruction in the how to build.md file, sitecore items are not getting created while trying to restore the sitecore items using serialization. I am doing the integration on sitecore 9.2.
There are no errors reported in the log.

**Comment by adeneys** [comment]
Version 4.0 has just been released, which adds support for all Sitecore 9.x versions. https://github.com/WeTeam/WeBlog/releases/tag/release%2F4.0

**Comment by basselissa** [comment]
Cool, thanks for the great work
