### ISSUE TITLE
create a package for SC9+

### ISSUE THREAD

**Issue by basselissa** [WeTeam/WeBlog#282]
Hello, 
Is there any hints or draft documentation on creating the package? i am trying to create a package for SC9.0

**Comment by rroman81** [comment]
would benefit from updated documentation as well.

**Comment by adeneys** [comment]
The `how to build.md` file has been updated with instructions on building the package. Version 4.0 has also just been released: https://github.com/WeTeam/WeBlog/releases/tag/release%2F4.0
