### ISSUE TITLE
Index_Update_IndexName=WeBlog-master

### ISSUE THREAD

**Issue by andyram2k** [WeTeam/WeBlog#285]
Hi,

I've noticed recently in our monitoring tools, that the Index_Update_IndexName=WeBlog-master is running quite a few times, in a single minute and is causing quite a queue in additional tasks.

e.g.

08:29:09 | Index_Update_IndexName=WeBlog-master | 59b625d0-f59e-4060-a486-13c15b4444e9;WSP-CMS-02-SiteCore CMS | Queued |   | sitecore\admin |   |   |   |   |   |   |   |   |   |  
  | 08:29:09 | Index_Update_IndexName=WeBlog-master | cffe9779-dd83-4304-b41f-e5a60850ad0b;WSP-CMS-02-SiteCore CMS | Running |   | sitecore\admin |   |   |   |   |   |   |   |   |   |  
  | 08:29:09 | Index_Update_IndexName=WeBlog-master | 92818058-a7d5-4b87-9c23-65ae53584ab5;WSP-CMS-02-SiteCore CMS | Queued |   | sitecore\admin |   |   |   |   |   |   |   |   |   |  
  | 08:29:09 | Index_Update_IndexName=WeBlog-master | 62a902c7-63ce-4ec0-81cc-63f8b8fdcb11;WSP-CMS-02-SiteCore CMS | Queued |   | sitecore\admin |   |   |   |   |   |   |   |   |   |  
  | 08:29:09 | Index_Update_IndexName=WeBlog-master | 64cccf80-784b-487c-9357-a811155622ae;WSP-CMS-02-SiteCore CMS | Queued |   | sitecore\admin |   |   |   |   |   |   |   |   |   |  
  | 08:29:09 | Index_Update_IndexName=WeBlog-master | cf3b6103-5038-42b3-a81f-25f349365f9a;WSP-CMS-02-SiteCore CMS | Queued |   | sitecore\admin |   |   |   |   |   |   |   |   |   |  
  | 08:29:09 | Index_Update_IndexName=WeBlog-master | 33f43527-c5c6-4411-aec4-0f0c48393496;WSP-CMS-02-SiteCore CMS | Queued |   | sitecore\admin |   |   |   |   |   |   |   |   |   |  
  | 08:29:09 | Index_Update_IndexName=WeBlog-master | 962fff99-eed9-41cd-9027-bd7d08a89845;WSP-CMS-02-SiteCore CMS | Queued |   | sitecore\admin |   |   |   |   |   |   |   |   |   |  
  | 08:29:09 | Index_Update_IndexName=WeBlog-master | 74bf3375-37a8-474f-ae1f-d18df1db7feb;WSP-CMS-02-SiteCore CMS | Queued |   | sitecore\admin |   |   |   |   |   |   |   |   |   |  
  | 08:29:09 | Index_Update_IndexName=WeBlog-master | 6d4cca3b-fd4b-4416-a504-6d32de48badb;WSP-CMS-02-SiteCore CMS | Queued |   | sitecore\admin |   |   |   |   |   |   |   |   |   |  
  | 08:29:09 | Index_Update_IndexName=WeBlog-master | 506a0afe-bd12-4d56-b322-2a03b536a622;WSP-CMS-02-SiteCore CMS | Queued |   | sitecore\admin |   |   |   |   |   |   |   |   |   |  
  | 08:29:09 | Index_Update_IndexName=WeBlog-master | f15dd3f9-f6ba-4409-92f9-9fb5e7e99a1d;WSP-CMS-02-SiteCore CMS | Queued |   | sitecore\admin |   |   |   |   |   |   |   |   |   |  
  | 08:29:09 | Index_Update_IndexName=WeBlog-master | 0fa46128-74c9-4a2a-b71c-c463265e6ae9;WSP-CMS-02-SiteCore CMS | Queued |   | sitecore\admin |   |   |   |   |   |   |   |   |   |  
  | 08:29:09 | Index_Update_IndexName=WeBlog-master | 55e7c552-ec0e-4022-a0c8-f1557375284b;WSP-CMS-02-SiteCore CMS | Queued |   | sitecore\admin

What could be causing this please? Our version is 8.1 initial release (before our move to 9.2 later on).

Thanks,

Andy

**Comment by adeneys** [comment]
Hi @andyram2k,
Sorry about the later reply.
From above, it would appear all those updates are on the master DB, so could it be possible you have some code running which is touching all those blog items causing them to be re-indexed?

**Comment by adeneys** [comment]
Is this issue still active?

**Comment by andyram2k** [comment]
Hi, it is on our current 8.1 instance, but we're moving to a 9.2 instance in the coming weeks, so i hope it will be resolved then. If not, i'll re-open the ticket. Please feel free to close.

**Comment by shaliksh** [comment]
> Hi, it is on our current 8.1 instance, but we're moving to a 9.2 instance in the coming weeks, so i hope it will be resolved then. If not, i'll re-open the ticket. Please feel free to close.

Andyram2k, 
Did you install on 9.2? We are on 9.1, not sure it works?

**Comment by andyram2k** [comment]
We’ve not just yet. The dev team on here have update files since then, so that should work on 9.1?

Sent from my Windows 10 device

**Comment by adeneys** [comment]
As advised above, closing this issue.
