### ISSUE TITLE
Error during serialization for sitecore 9.2

### ISSUE THREAD

**Issue by solkararif** [WeTeam/WeBlog#288]
Hi @adeneys ,

i am facing the below error while trying to serialize the sitecore items on the core database.

\App_Data\serialization\core\sitecore\client\Applications\WeBlog\Import.item ---> System.Exception: Error reading item: /sitecore/client/Applications/WeBlog/Import ---> System.Exception: Length of field content does not match the content-length attribute. Field name: __Renderings, field id: f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e..

**Comment by adeneys** [comment]
Hi @solkararif,
This normally occurs when the line endings are incorrect. Check the file and see if it's using Windows line endings (\r\n) or Unix line endings (\n). If you're using notepad++ this can easily be seen in the bottom bar on the right hand side. Ensure the line endings are Windows (\r\n) before running deserialization.

**Comment by solkararif** [comment]
hi @adeneys 

Thank you for your prompt responses and quicker fixes, I was able to explore the weblog module with sitecore 9.2. We are planning to extend this module, are there any plans to create a nuget package that could be extended for different sitecore 9X version.

**Comment by adeneys** [comment]
Hi @solkararif,
We release WeBlog as Sitecore packages, which you can find on the [releases page](https://github.com/WeTeam/WeBlog/releases).
We haven't really considered using NuGet as a release mechanism as WeBlog requires config files and items as well which must be deployed to Sitecore, and Sitecore doesn't have a mechanism to install packages from NuGet.
