### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by techphoria414** [WeTeam/WeBlog#29]
Add responsive CSS to techphoria theme, and/or mobile device layer as needed.

http://sdn.sitecore.net/SDN5/Forum/ShowPost.aspx?PostID=50557

**Comment by adeneys** [comment]
New themes are responsive. Verify once the themes have been merged in.

**Comment by alan-null** [comment]
Emulators shows that everything works fine.
![image](https://cloud.githubusercontent.com/assets/6848691/15027935/844e1122-1246-11e6-98f4-823e0fd6f050.png)
