### ISSUE TITLE
Error while submitting comments in sitecore 9.2

### ISSUE THREAD

**Issue by solkararif** [WeTeam/WeBlog#290]
hi @adeneys ,

Facing issue while submitting the comments on the logs that has been created.I have added the endpoint address in the web.config as per the configuration mention in the WeBlog.delivery.config.

Error:

Object reference not set to an instance of an object.
Description: An unhandled exception occurred.

Exception Details: System.ServiceModel.FaultException`1[[System.ServiceModel.ExceptionDetail, System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]: Object reference not set to an instance of an object.

![CommentError](https://user-images.githubusercontent.com/33153682/74434188-e2274f80-4e87-11ea-8352-3315f06cadcd.png)

**Comment by solkararif** [comment]
Hi @adeneys,

The issue occur while adding comment to any blog.
The issue seems to be the Context object is null while creating the cache object and getting the item.

The file is ProfanifityFilterCache.cs

`Line 13:   get { return "wordlist_" + Context.Database.Name; }`

**Comment by adeneys** [comment]
Hi @solkararif,
Thanks for the info, and tracking down the source of the issue.
It looks like a few of the profanity filter processors are having issues when invoked through the service. I'll need to create a fix and release an update to address the issue.

In the meantime, if you're happy to run without the profanity filter, just comment the `Sitecore.Modules.WeBlog.Pipelines.CreateComment.ProfanityFilter` out of the `weblogCreateComment` pipeline. This will disable the filter and will allow the comment to be submitted.

**Comment by solkararif** [comment]
Hi @adeneys,

Thank you it has been fixed

**Comment by adeneys** [comment]
Thanks for confirming @solkararif,
FYI this fix will be included in the 4.0.1 release which I'm working on putting out at the moment.
