### ISSUE TITLE
blogs stop appearing

### ISSUE THREAD

**Issue by Nikita-cap** [WeTeam/WeBlog#297]
Hello,
We have observed several times that the blogs stop appearing on the page and we have to rebuild the index in order to fix this.
We are using sitecore version 9.1.1 with SXA version 1.8.
Do we have to rebuild indexes on every build to the environment?

**Comment by adeneys** [comment]
Hi @Nikita-cap,
WeBlog simply uses the Content Search APIs from Sitecore. It has no requirements itself for requiring indexes to be rebuilt manually, although search providers themselves might have requirements about when the indexes must be built. You asked about rebuilding the index "on every build to the environment". It may depend on what you're doing in your build. Generally the search providers require an initial index build to create the WeBlog indexes after which they'll stay up-to-date as changes are made.

Do the blog listings only disappear after you deploy to your environment?

**Comment by Nikita-cap** [comment]
Hi Adeneys,

Thank you for your response.
No, we do not have to rebuild on every build. I hope it was just a one time issue :) we are using Solr which is the Sitecore's default search provided.
Additionally, I wanted to confirm if weblog should also be compatible with sitecore 9.1 with SXA 1.8.

**Comment by adeneys** [comment]
Thanks for letting me know @Nikita-cap .
WeBlog has been built against and tested with Sitecore 9.1.
I've not tested WeBlog with SXA, though I don't expect any issues. WeBlog has been designed to be used inside other sites.

If you find any issues in using WeBlog with SXA please let us know.

**Comment by alan-null** [comment]
@Nikita-cap if you are using SXA you might want to check [this](https://alan-null.github.io/2017/12/sxa-blog).
SXA presence shouldn't influence WeBlog.
