### ISSUE TITLE
Polish language support

### ISSUE THREAD

**Issue by avrohit2000** [WeTeam/WeBlog#306]
While import and publish need a support for polish. At the moment whilst using 4.1 for sitecore 9.0 words get converted to english when xml contains polish letter.

**Comment by adeneys** [comment]
@avrohit2000 Could you please provide a full reproduction scenario? You mentioned import, so I assume you're talking about the WordPress import functionality. I just validated that Polish characters in the WordPress XML export file are imported and preserved.
![polish-char-import](https://user-images.githubusercontent.com/1198054/97508543-fab6a600-19d3-11eb-92be-7278b77637dd.png)
