### ISSUE TITLE
Getting Critical Error on Experience Editor (Sitecore 9.2)

### ISSUE THREAD

**Issue by AmitaRaiDev** [WeTeam/WeBlog#308]
![ExpEditorIssue](https://user-images.githubusercontent.com/35682645/109334035-311f0780-7886-11eb-92eb-55895070cbea.png)

**Comment by adeneys** [comment]
What version of WeBlog are you using?
Any errors in the logs?
Can you provide a list of steps to reproduce the error?

**Comment by AmitaRaiDev** [comment]
Error is coming in js files which are present at weblog/experienceEditor/Commands.

Do we have any option for removing WeBlog from Experience editor?

**Comment by adeneys** [comment]
You should be able to remove WeBlog from the Experience Editor by following these steps:

1. Delete the `/sitecore/content/Applications/WebEdit/Ribbons/WebEdit/WeBlog` item from the `core` database.
2. Disable the `/App_Config/Include/WeBlog.ExperienceEditor.config` config patch file by changing the file extension to `disabled`.

**Comment by amitaRai** [comment]
Thank you for your quick response.
