### ISSUE TITLE
Error 405 when submit comment 

### ISSUE THREAD

**Issue by idmedia-anders** [WeTeam/WeBlog#310]
Hello all

We are using the module for our project.
We are using **Sitecore 9.1** and have installed the module as a package.
We are using a **CM** and **CD** environment.
The web.config for CD and the web.config for CM were both added with the config from the weblog.config.

For our CM web.config we used this config:
WCF Server (Sitecore authoring server)
```
<configuration>
  <system.serviceModel>
    <serviceHostingEnvironment aspNetCompatibilityEnabled="true"/>
    <behaviors>
      <serviceBehaviors>
        <behavior name="Sitecore.Modules.WeBlog.Services.CommentServiceBehaviour">
          <serviceMetadata httpGetEnabled="true" />
          <serviceDebug includeExceptionDetailInFaults="true" />
        </behavior>
      </serviceBehaviors>
    </behaviors>
    <services>
      <service name="Sitecore.Modules.WeBlog.Services.CommentService"
        behaviorConfiguration="Sitecore.Modules.WeBlog.Services.CommentServiceBehaviour">
        <endpoint address="" binding="wsHttpBinding" contract="Sitecore.Modules.WeBlog.Services.ICommentService">
          <identity>
            <dns value="localhost" />
          </identity>
        </endpoint>
      </service>
    </services>
  </system.serviceModel>
</configuration>
```

and for the CD web.config
WCF Client (Sitecore delivery server)
```
<configuration>
  <system.serviceModel>
    <client>
      <endpoint address="http://[authoring server address]/sitecore modules/web/WeBlog/Comment.svc"
        binding="wsHttpBinding" contract="Sitecore.Modules.WeBlog.Services.ICommentService"
        name="WeBlogCommentService">
        <identity>
          <dns value="localhost" />
        </identity>
      </endpoint>
    </client>
  </system.serviceModel>
</configuration>
```

At the "<endpoint address="http://**[authoring server address]** [...]"
we have entered our CM address.

Now our problem is that when submitting a comment we get a 405 error.
"405 - Method not allowed"

Did we configure something wrong at this point or is there something else that needs to be adjusted?

**Comment by adeneys** [comment]
It's likely you're missing Windows Features which allow activating WCF services over HTTP.

![image](https://user-images.githubusercontent.com/1198054/111901550-02fba480-8a8d-11eb-9102-840c66a57282.png)

Try enabling the `HTTP Activation` features inside the `.NET Framework` categories as shown in the screenshot above.
