### ISSUE TITLE
Support for Sitecore 10.1

### ISSUE THREAD

**Issue by amarbaktha** [WeTeam/WeBlog#314]
Please let us know the availability of WeBlog module for Siteore 10.1.

**Comment by adeneys** [comment]
I'm working on this right now. I'm hoping to get a release out in the next week or 2.

**Comment by amarbaktha** [comment]
Thank you, keep us apprised!

**Comment by adeneys** [comment]
Release 4.2 has just been created which adds support for Sitecore 10.1: https://github.com/WeTeam/WeBlog/releases/tag/release%2F4.2

**Comment by amarbaktha** [comment]
Thank you @adeneys!
