### ISSUE TITLE
10.2

### ISSUE THREAD

**Issue by everdoorn** [WeTeam/WeBlog#321]
Are there any plans to update the 4.2 release to support 10.2 or is there a new release expected which would support 10.2? It appears others have installed the 10.1 supported release on a 10.2 environment and it worked for the most part with an error in the comments functionality that could be worked through if need be. 

Thanks!

**Comment by adeneys** [comment]
There are currently no plans for further development on WeBlog. I would encourage you to fork the repo and continue your own development on the module.
