### ISSUE TITLE
Wordpress Import: Won't allow XML Upload

### ISSUE THREAD

**Issue by techphoria414** [WeTeam/WeBlog#33]
When attempting to upload a Wordpress XML file, Sitecore dialog presents the error

"[filename]" is not a ZIP file

Workaround is to place the file directly into the $(dataFolder)\packages directory and use "Browse" to choose it instead.

![Screen Shot 2013-04-03 at 6 08 14 PM](https://f.cloud.github.com/assets/1562106/336822/678c7cba-9cb3-11e2-9c5e-5c9d93a394fb.png)

**Comment by alan-null** [comment]
Issue solved. New SPEAK app allows you to upload xml files
