### ISSUE TITLE
Create release for Sitecore 7

### ISSUE THREAD

**Issue by adeneys** [WeTeam/WeBlog#39]
Create Sitecore 7 release to make use of Sitecore 7 features such as item buckets for both blog posts and comments.

Sitecore 6.6 and previous must still be supported, so updates for Sitecore 7 features must be done in a way to still allow the current features to operate without the Sitecore 7 features.

**Comment by alan-null** [comment]
Version with  SC7 support released.
More information here: [Release 2.4](https://github.com/WeTeam/WeBlog/releases/tag/release%2F2.4)
