### ISSUE TITLE
Invalid shift value in prefixCoded string (is encoded value really an INT?)

### ISSUE THREAD

**Issue by dsandsqis** [WeTeam/WeBlog#49]
I receive the following when trying to access a WeBlog item in Sitecore v6.6. I can rebuild the index without incident but rendering an entry or blog listing page produces this error via call to Lucene.
-------

Server Error in '/' Application.

Invalid shift value in prefixCoded string (is encoded value really an INT?)

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.FormatException: Invalid shift value in prefixCoded string (is encoded value really an INT?)

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[FormatException: Invalid shift value in prefixCoded string (is encoded value really an INT?)]
   Lucene.Net.Util.NumericUtils.PrefixCodedToInt(String prefixCoded) +266
   Lucene.Net.Search.AnonymousClassIntParser1.ParseInt(String val) +229
   Lucene.Net.Search.IntCache.CreateValue(IndexReader reader, Entry entryKey) +644
   Lucene.Net.Search.Cache.Get(IndexReader reader, Entry key) +877
   Lucene.Net.Search.FieldCacheImpl.GetInts(IndexReader reader, String field, IntParser parser) +260
   Lucene.Net.Search.IntCache.CreateValue(IndexReader reader, Entry entryKey) +1357
   Lucene.Net.Search.Cache.Get(IndexReader reader, Entry key) +877
   Lucene.Net.Search.FieldCacheImpl.GetInts(IndexReader reader, String field, IntParser parser) +260
   Lucene.Net.Search.IntComparator.SetNextReader(IndexReader reader, Int32 docBase) +129
   Lucene.Net.Search.OneComparatorNonScoringCollector.SetNextReader(IndexReader reader, Int32 docBase) +96
   Lucene.Net.Search.IndexSearcher.Search(Weight weight, Filter filter, Collector collector) +312
   Lucene.Net.Search.IndexSearcher.Search(Weight weight, Filter filter, Int32 nDocs, Sort sort, Boolean fillFields) +1910
   Lucene.Net.Search.IndexSearcher.Search(Weight weight, Filter filter, Int32 nDocs, Sort sort) +111
   Lucene.Net.Search.Hits.GetMoreDocs(Int32 min) +395
   Lucene.Net.Search.Hits..ctor(Searcher s, Query q, Filter f, Sort o) +404
   Lucene.Net.Search.Searcher.Search(Query query, Sort sort) +110
   Sitecore.Modules.WeBlog.Search.Searcher.Execute(QueryBase query, Int32 maximumResults, Action`2 func, String sortField, Boolean reverseSort) +577
   Sitecore.Modules.WeBlog.Managers.EntryManager.GetBlogEntries(Item blog, Int32 maxNumber, String tag, String category, String datePrefix) +1038
   Sitecore.Modules.WeBlog.Managers.EntryManager.GetBlogEntries() +51
   Sitecore.Modules.WeBlog.Layouts.BlogPostList.BindEntries(String tag) +275
   Sitecore.Modules.WeBlog.Layouts.BlogPostList.Page_Load(Object sender, EventArgs e) +452
   System.Web.Util.CalliHelper.EventArgFunctionCaller(IntPtr fp, Object o, Object t, EventArgs e) +25
   Sitecore.Modules.WeBlog.Layouts.BaseSublayout.OnLoad(EventArgs e) +90
   System.Web.UI.Control.LoadRecursive() +71
   System.Web.UI.Control.LoadRecursive() +190
   System.Web.UI.Control.LoadRecursive() +190
   System.Web.UI.Control.LoadRecursive() +190
   System.Web.UI.Control.LoadRecursive() +190
   System.Web.UI.Control.LoadRecursive() +190
   System.Web.UI.Control.LoadRecursive() +190
   System.Web.UI.Control.LoadRecursive() +190
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3064

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.1016

**Comment by adeneys** [comment]
I think I worked this one out. I was finally able to reproduce the issue locally.

@benbartle is correct above. The issue is to do with the `$date` token used in standard values for the `entry date` field. If you end up with items in your content tree that where not created with that field present (such as is the case with a migration or pasting item XML) then the `$date` token will not be replaced as that only gets replaced at item creation. Lucene will then index that as the date field value. That in itself will not cause the issue, it's also because in WeBlog we use sorting when running the search query to make sure we get back a sorted list of items.

Easiest way to fix this issue is as @benbartle points out, fill in the `entry date` of all entry items. Another solution would be to remove the `$date` token from standard values of the entry template. And after whatever change you make, rebuild the index.
