### ISSUE TITLE
Allow individuals to subscribe to a specific blog.

### ISSUE THREAD

**Issue by mariellamontoni** [WeTeam/WeBlog#51]
Individuals could subscribe to a specific blog. It would be interesting if the individual could also choose the categories of the blog he would like to subscribe. So he would get posts regarding only on those categories... This way we could analyze better the interests of the individuals that read the blog.

**Comment by alan-null** [comment]
@mariellamontoni 
This is already supported without additional implementation.

By default you Feed will be created with the following Sitecore query:
```
query:.././/*[@@templateid='{5FA92FF4-4AC2-48E2-92EB-E1E4914677B0}']
```

You can create personalized RSS Feed (WeBlog supports multiple RSS feeds, all will be listed in Syndication component)
Here is my example:
```
/sitecore/content/Home/blog//*[@@templatename='BlogEntry' and ((contains(@Tags, 'tag1') or contains(@Tags, 'tag2')) or (@Category = '{B712C6AF-B531-4A1F-B8BD-0A4D397FD6A3}'))]
```
This will aggregate all blog posts with at least one of the tags: **tag1**, **tag2** or Category with a given ID. As you can see you can create very advanced filters.

For more Sitecore query examples please refer [here](https://sdn.sitecore.net/upload/sdn5/developer/using%20sitecore%20fast%20query/using%20sitecore%20fast%20query001.pdf).

To create additional Feed use the same template as WeBlog does.(*/sitecore/templates/System/Feeds/RSS Feed*)

Remember that you can easily cache your feed results if you have really heavy query:
![image](https://cloud.githubusercontent.com/assets/6848691/12404498/5fba0fae-be3c-11e5-8382-6020fe04642c.png)
