### ISSUE TITLE
Comments in a Multi-server Environment

### ISSUE THREAD

**Issue by venkatraman2014** [WeTeam/WeBlog#56]
Hi,
I am using we-blog in my project.
I am having following issues in weblog:-
1) I am not able to post comment in the blog on live site.My live site is having 1 CM server and 2 CD server.I made changes in the weblog.config which are mentioned in the "https://github.com/WeTeam/WeBlog/wiki/Multi-Server-Setup".
I am having the below error .
Could not find endpoint element with name 'WeBlogCommentService' and contract 'Sitecore.Modules.WeBlog.Services.ICommentService' in the ServiceModel client configuration section. This might be because no configuration file was found for your application, or because no endpoint element matching this name could be found in the client element.

2)The captcha used in the post comment does not appear all the time randomly it shows broken image in the chrome and mozilla.

**Comment by alan-null** [comment]
Closed due to lack of activity.
