### ISSUE TITLE
WeBlog show more posts in post list doesn't display any more content

### ISSUE THREAD

**Issue by GBDurrary** [WeTeam/WeBlog#61]
Visible at www.healthspan.co.uk/news/categories/healthspan-heroes

The code is supposed to show five more posts and add ?count=15 or whatever to the end of the url. It uses JS to display extra items on the first click, but doesn't change the url, and because it loads data from part of the page, on postback it throws an error (Which I have caught) meaning it only works the first time you click the button.

**Comment by alan-null** [comment]
HI @GBDurrary,

I don't even know if you are still interested what is wrong there, after almost one year but I will try to explain it anyway,

I am pretty sure that WeBlog version there contains following **functions.js** file
https://github.com/WeTeam/WeBlog/blob/50a699b5b8d01675cbdda2dc792ae2f2e98ad665/Website/sitecore%20modules/web/WeBlog/Includes/functions.js

I was able to find broken part:
```javascript
function(n) {
    n(document).ready(function() {
        n(".wb-view-more", "#wb-view-more-wrapper").click(function() {
            var t = n(this),
                r = t.next(".wb-loading-animation"),
                u = n("#wb-entry-list ul"),
                i,
                f;
            return t.hide(),
                r.show(),
                n.url.setUrl(document.location),
                i = {
                    startIndex: u.children().length,
                    blogAjax: 1
                },
                n.url.param("tag") != null && (i.tag = n.url.param("tag")),
                f = n.url.setUrl(t.attr("href")).attr("path"),
                n.get(f, i, function(n) {
                    var i = jQuery(n).find("ul li");
                    u.append(i);
                    r.hide();
                    t.show()
                }), !1
        });
        n("#wb-archive .wb-year, #wb-archive .wb-month").click(function() {
            var t = n(this);
            t.next("ul").toggle("200");
            t.toggleClass("expanded")
        })
    })
}
```
source: http://d2zv2b08ioi6ch.cloudfront.net/scripts/new-design

Feature will work when the following line
```javascript
 t.show()
```
becomes
```javascript
if (i.length>0) t.show();
```

## Solutions
You've got two options, pick one:

##### Solution 1. 
Please change your **function.js** version with this one:
https://github.com/WeTeam/WeBlog/blob/master/Website/sitecore%20modules/web/WeBlog/Includes/functions.js


##### Solution 2. 
Please update your **functions.js** file like it was done in this commit:
https://github.com/WeTeam/WeBlog/commit/781bfed94f6368e4f641dbe7e7148f0b0774b399#diff-db0f126880aa6a9b49da0db2dffe1102R25

Simply change
```javascript
viewMore.show();
```
into
```javascript
if (posts.length>0)viewMore.show();
```
