### ISSUE TITLE
MVC Support!

### ISSUE THREAD

**Issue by dmeadnavarts** [WeTeam/WeBlog#62]
Hi Weblog,

We use WeBlog extensively.  Any plans to support MVC?  I checked Marketplace and no word about it.  We need WeBlog for MVC since we're doing MVC-only for Sitecore now unless we have to.  We care about Sitecore 7.x only, really.  Thanks for this Blog feature for the community!!

**Comment by adeneys** [comment]
We've updated our plans to include full MVC support in one of our next releases.

We don't want any duplicate code, so any logic currently contained within any presentation component must be extracted to a separate API which can be called from the sublayout and the corresponding MVC view.

**Comment by email-aveeral** [comment]
Is weblog on MVC?
If yes, Can i have the new package for installation and github path for it?

**Comment by alan-null** [comment]
hi @email-aveeral 

We are still working on MVC support for WeBlog (let's say current progress is 90-95%). 
I think this feature will be a part of the next release. 
Currently we do not have any beta package for that.

**Comment by fluxdigital** [comment]
Hi Weblog (@adeneys),

I'm just wondering if you are able to release the MVC version yet? I've just downloaded the latest version and it all seems to be webforms only still.

thanks

Adam

**Comment by alan-null** [comment]
Hi @fluxdigital 

Because MVC is not a part of any public release.
This feature will be included in the next release. 
Official release date is unknown yet. I assume it should happen soon. At the moment we just need to finish one milestone (themes). It is currently being in review phase.

**Comment by adeneys** [comment]
As Alan said, we're working on getting the next release out ASAP which will include MVC support. If you can't wait for the release you can checkout the develop branch.

**Comment by fluxdigital** [comment]
Hi @adeneys & @alan-null - thanks for your quick response. Do you have a time frame for the next release? I'm not looking for concrete dates but just an idea. e.g in the next 2-3 months or end of the summer or autumn etc.

**Comment by alan-null** [comment]
@fluxdigital 
Our target is to do it ASAP, probably in the next 2-3 months, but let's do not treat it like a deadline.

**Comment by AshishRanjan31** [comment]
Hi Team,
Can please any one provide me sitecore MVC pkg.
I downloaded sitecore pkg that belongs to webforms.
It's urgent i need this one.
Thanks in adv.

**Comment by alan-null** [comment]
@AshishRanjan31 
Starting from [3.0](https://github.com/WeTeam/WeBlog/releases/tag/release%2F3.0), WeBlog  supports MVC 

Please, make sure you download the most recent version: 
https://github.com/WeTeam/WeBlog/releases
