### ISSUE TITLE
Needs up-to-date references to new versions of MSCAPTCHA and RECAPTCHA

### ISSUE THREAD

**Issue by sean-nuckolls** [WeTeam/WeBlog#63]
If both WeBlog and Sitecore's Web Forms for Marketers 2.5 are installed, there is a conflict. If WFFM is allowed to overwrite the MSCAPTCHA DLL, WeBlog will throw a stack trace on the version. If the older version that ships WeBlog is allowed to stay, WFFM will stack trace.

**Comment by adeneys** [comment]
References for MSCaptcha.dll have been updated to the versions used in the lastest versions of WFFM to ensure compatibility.

A new issue #94 has been opened to update the recaptcha code as this is not a simple update. The library we're currently using is the latest version of that library and it does not support recaptcha v2.
