### ISSUE TITLE
Comment form does not accept apostrophes. 6.6 Sitecore

### ISSUE THREAD

**Issue by JenKove** [WeTeam/WeBlog#64]
If I enter a comment with a contraction like "Don't write in contractions if you don't want to see this error"
<p>I've noticed that other sites using this blog software also have the issue. Is there any easy fix to escape the apostrophe and quote characters from a form before posting? Failing that, I'm currently looking for the area where we store error messages and hoping to put one up. </p>
================================================

ERROR THAT RESULTS (<strong>UNTIL YOU REMOVE & REPOST</strong>)

Server Error in '/' Application.

"]" expected at position 163.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: Sitecore.Data.Query.ParseException: "]" expected at position 163.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[ParseException: "]" expected at position 163.]
   Sitecore.Data.Query.QueryParser.Raise(String error) +209
   Sitecore.Data.Query.QueryParser.GetPredicate() +212
   Sitecore.Data.Query.QueryParser.GetElement() +471
   Sitecore.Data.Query.QueryParser.GetNode() +392
   Sitecore.Data.Query.QueryParser.GetDescendants() +131
   Sitecore.Data.Query.QueryParser.GetPathStep() +50
   Sitecore.Data.Query.QueryParser.GetQuery() +138
   Sitecore.Data.Query.QueryParser.GetQueries() +33
   Sitecore.Data.Query.QueryParser.DoParse(String query) +195
   Sitecore.Data.DataProviders.Sql.FastQuery.QueryToSqlTranslator.TranslateQuery(String query, CallContext callContext, ParametersList parameters) +62
   Sitecore.Data.DataProviders.Sql.SqlDataProvider.QueryFast(String query, CallContext context) +122
   Sitecore.Data.DataProviders.DataProvider.SelectIDs(String query, CallContext context, DataProviderCollection providers) +135
   Sitecore.Data.DataManager.SelectItems(String query, Boolean& processed) +90
   Sitecore.Data.Database.SelectItems(String query) +105
   Sitecore.Modules.WeBlog.Pipelines.CreateComment.DuplicateSubmissionGuard.Process(CreateCommentArgs args) +315
   (Object , Object[] ) +80
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +191
   Sitecore.Modules.WeBlog.Managers.CommentManager.AddCommentToEntry(ID entryId, Comment comment, Language language) +148
   Sitecore.Modules.WeBlog.Managers.CommentManager.SubmitComment(ID entryId, Comment comment, Language language) +464
   Sitecore.Modules.WeBlog.Layouts.BlogSubmitComment.buttonSaveComment_Click(Object sender, EventArgs e) +497
   System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +154
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3707

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.1016

**Comment by adeneys** [comment]
This has been fixed and will be available in release 2.4
