### ISSUE TITLE
Multiple WeBlog Instances within One Sitecore Instance - Some Blogs Not Showing Posts

### ISSUE THREAD

**Issue by ufpian** [WeTeam/WeBlog#67]
We've been working with WeBlog successfully for a few months until recently, when I noticed that new posts weren't being picked up by some of the blogs.  We have three WeBlog instances attached to three site nodes (among many other sites).  One of these blog instances uses a unique post template, and the other two follow one template.  The two other blogs have trouble accurately refreshing their blog listings, sometimes even showing up blank with no posts.  The solitary blog has no issues properly reflecting all posts.  All blogs reflect full and accurate RSS feeds, indicating to me that at least some posts have the correct templates and are being found.

I've verified that each blog has the appropriate template keyed in as its alternate template, and that each post has the proper template to be picked up by WeBlog.  Each post appears to be properly seated in an appropriate year and month.  The template that the two blogs with issues use is nothing more than a duplicate of the template used by the working blog, but with a different name (and different standard presentation layout pieces). I've rebuilt the WeBlog search index to no avail.  It seems like this is a caching issue, but I believe I've done everything to clear every cache (including the Sitecore cache).  Is there anything else I might do to jump start the other two blogs that they might start picking up their posts again?  Is this module meant to run multiple blogs under one Sitecore instance?

**Comment by adeneys** [comment]
WeBlog does support multiple blogs.
Is it just the new posts that have issues? Could this be an index refresh issue?

**Comment by ufpian** [comment]
We actually just recently resolved this on our own through a lot of banging our heads against the wall.  As it turned out, our config file which indicates the items to be searched had an error.  Specifically, the named nodes for each template were redundant.  After changing them to a unique node name, both templates started showing up as returned results.

![capture](https://cloud.githubusercontent.com/assets/10515979/6147920/6a5df0bc-b1ca-11e4-9fdd-0ce51f4699c7.JPG)

"acEntry" and "ufpEntry" were both still "myentry", and both need to have unique names, unbeknownst to us.  Everything seems to be in working order now.  Thanks for replying all the same.
