### ISSUE TITLE
Sitecore 8

### ISSUE THREAD

**Issue by LonghornTaco** [WeTeam/WeBlog#69]
Has anyone tested the WeBlog module in Sitecore 8 yet?

**Comment by fastcpu88** [comment]
If you look at patch-1 you will see updates to support Sitecore 7.5 that version should work with Sitecore 8.0.  I altered it to use the Sitecore search provider and have tested it with Coveo.  I have not tested it with Lucene.  If you have issues and want some help with 8.0 email us at chris.williams@techguilds.com or dennis.augustine@techguilds.com and we can assist you with any Sitecore 8 issues with Weblog.

**Comment by josemarcenaro** [comment]
Hi fastcpu - excuse me for the dumb question but... how do we get patch-1 ? Is that what we get if we pull the latest commit on master? Or it's available on Sitecore Marketplace?
Thanks in advance

**Comment by fastcpu88** [comment]
It is compiled against 7.5 and works with coveo. I have not tested it with lucene.  If you test with lucene and its good please add it to git and let me know :) https://docs.google.com/file/d/0B976zuito-ZITDRsQXVQQ1ZQa2M/edit?usp=docslist_api

**Comment by josemarcenaro** [comment]
Thank you very much!
I will let you know once I’ve tested it with Lucene.

**Comment by surendrad79** [comment]
Hi,
This is "Surendra Dubey", i have tested WeBlog with Sitecore 8.0 and able to create blogs item and entries but while previewing i am getting below error
Could not find add method: AddCrawler (type: Sitecore.ContentSearch.LuceneProvider.LuceneIndex)
please find attached updated code base 

and weblog.config file

**Comment by alan-null** [comment]
WeBlog with Sitecore 8 support released.
Follow [this](https://github.com/WeTeam/WeBlog/releases/tag/release%2F2.4) link to learn more
