### ISSUE TITLE
Poll Module Compatibility with Sitecore 8.0

### ISSUE THREAD

**Issue by surendrad79** [WeTeam/WeBlog#74]
Hi,
Can anyone help me, available Poll Module will work with Sitecore 8.0, i have to implement Poll functionality for one of my projects
https://marketplace.sitecore.net/Modules/Poll_Module.aspx?sc_lang=en

**Comment by adeneys** [comment]
I think you're looking for the Poll module repository over at https://github.com/JimmieOverby/SitecorePollModule/issues

**Comment by surendrad79** [comment]
Thanks for replying adeneys, but this is not working with Sitecore 8.0, i have installed this module on Sitecore 8.0 and able to assign Poll template but this is not opening Poll Wizard.
