### ISSUE TITLE
Content Search for Sitecore 7.0 is not working.

### ISSUE THREAD

**Issue by alan-null** [WeTeam/WeBlog#79]
**How to reproduce**
1. Install Sitecore 7.0
2. Install WeBlog 2.3 for SC70
3. Build WeBlog project with target sc70

**Actual result:**
You are not able to see any posts or following error will be thrown: *WeBlog index cannot be found*

**Comment by adeneys** [comment]
I believe this issue was due to the legacy Lucene Search config still being included when the project is built. This should be fixed in the feature/content_search_support branch.

**Comment by alan-null** [comment]
I think you are right. As far as I remember I didn't notice that there was already some new dev brach.
