### ISSUE TITLE
WeBlog buttons from the ribbon are not visible in Sitecore 8.

### ISSUE THREAD

**Issue by alan-null** [WeTeam/WeBlog#81]
Like in the title. WeBlog buttons are not visible in Experience Editor for Sitecore 8+.

**Comment by rendermouse** [comment]
Are you using Chrome? In Chrome, many Sitecore ribbon items are missing for me. I had to use IE11.

**Comment by alan-null** [comment]
Hi @rendermouse,
Sorry, I somehow missed your message . Yes, I am using chrome, but it is not the case. Since Sitecore 8 ribbon buttons need to be updated with additional layout details to render properly. If you are interested please see my pull request.
