### ISSUE TITLE
seo issue

### ISSUE THREAD

**Issue by Rezakhatami** [WeTeam/WeBlog#84]
how can I improve www.tahlildadeh.com seo?
it is for Iranian web developers( website language is Farsi/Persian ) 
I read about title,content,url,slug,h1 tag and lot of things.
and I used all of them but the alexa rang doesn't change.
please tell me more about seo.

**Comment by adeneys** [comment]
This project is for the WeBlog module for Sitecore, not weblogs in general. If you have specific issues related to the WeBlog module for Sitecore please log those.
