### ISSUE TITLE
Archive in non-English versions

### ISSUE THREAD

**Issue by DanielStillwaggon** [WeTeam/WeBlog#86]
It appears that the "Archive" sidebar feature has issues when dealing with multiple language versions. We have created Chinese versions of our blog entries and now the archive has a list of years stretching back to year 0 (that is 2015 separate years listed with no blogs under any except the few in 2015 that we have created.) The blogs from 2015 are displayed properly, but the years make it unusable.

Where is it pulling the globalized date list? It seems to be getting null values for the dates even though the field has been marked as shared.

**Comment by adeneys** [comment]
Which WeBlog version are you using? In the latest code the years for the sidebar are taken from the years the entries span. You can check out the methods in the codebehind for the Archive sublayout: https://github.com/WeTeam/WeBlog/blob/master/Website/layouts/WeBlog/Sidebar/Archive.ascx.cs

I've tried this locally, creating the entries in a non-English language (German), and the archive behaved as it should.

**Comment by DanielStillwaggon** [comment]
I looked through the logic and it appears that there may be an issue using this with the language fallback module. It appears that you are using your own globalization module that looks to different places but is reading "null" values as having a valid year. We have "Entry Date" set as a shared value with most of the rest of the blog content set to allow fallback (so that all of the blogs appear on our Chinese site, but they appear in English until the translators can get to them.

We are using version 2.3 of Weblog from DLL (it is not integrated into our project at this point.)

**Comment by alan-null** [comment]
@DanielStillwaggon 

It appears to be a language fallback module issue. 
Language Fallback is dedicated for Sitecore CMS <6.5, which means for versions which are not supported by WeBlog anymore.

Just one hint:
Make sure you setup fallback for EntryDate fields and verify if your blog root **__Created** field has the same value for both versions (I assume it hasn't if you created second language version later)

In version **2.3** *Archive component* was build with usage of this system field (shortly, if you had post with older date than your blog root created date if was not included into archive).
Problem fixed here:
https://github.com/WeTeam/WeBlog/commit/8a5d95c97b6c5e79b7fc8afc3b08bb7e5472b8d8#diff-15e1bab60ad2ca4e1c420d72ae96fd96L83

If you are using Sitecore 7.0+ now, you can update your instance with the [newest release](https://github.com/WeTeam/WeBlog/releases/tag/release%2F2.4)
