### ISSUE TITLE
Consider migrating to JsonDataProvider

### ISSUE THREAD

**Issue by AlenPelin** [WeTeam/WeBlog#87]
For development purpose, consider migrating to [Sitecore.JsonDataProvider](https://github.com/Sitecore/Sitecore.JsonDataProvider) which is in Release Candidate state.

**Comment by alan-null** [comment]
The linked project is no longer developed.
![image](https://user-images.githubusercontent.com/6848691/47603167-8dd53380-d9e8-11e8-8f55-0c149134ac44.png)
