### ISSUE TITLE
Add serialization to project

### ISSUE THREAD

**Issue by AlenPelin** [WeTeam/WeBlog#92]
I suggest adding serialization items to the project to be able to search for literals (understand where specific keyword is used) and enable Search&Replace technique during refactoring. It is better to do that alongside with #87

**Comment by adeneys** [comment]
I started on this but decided against it. The items in WeBlog are fairly stable, changing much less often than on a site build. Changing to a different serialization format will introduce quite a bit of complexity which will need to be maintained, but we won't get much value out of it at this stage of the project.
