### ISSUE TITLE
Blog entries returned in wrong order

### ISSUE THREAD

**Issue by alan-null** [WeTeam/WeBlog#95]
**How to reproduce:**
1. Install Sitecore 7.0, (rev. 140120)
2. Install WeBlog
3. Create new blog and add some posts
4. Modify entry dates so you can see if sorting works fine

**Actual result:**
* Posts are sorted in reverse order (starting from the oldest one)
* Archive component does  not render anything

If you confirm that package was created without this https://github.com/WeTeam/WeBlog/commit/da4403117d57c25a98870c5043b8a78b2b088d0d commit we can close it as resolved. Checked code via dotPeetk and it seems that fix is not there yet.

**Comment by adeneys** [comment]
Pulled mentioned commit. Release packages will be rebuilt
