### ISSUE TITLE
Problem with field wrapping in Experience Editor

### ISSUE THREAD

**Issue by alan-null** [WeTeam/WeBlog#96]
[Steps to reproduce](https://dl.dropboxusercontent.com/u/191345630/Stecore/WeBlog/field%20wrapping.gif)
As you can see if you add some paragraphs into a field you will not be able to edit it from Experience Editor anymore.
Here is an introduction field raw content.
```html
some text
<p>Lets break it.</p>
```

**Additional info**:
Bug doesn't appear on Sitecore 7.0

For more info see pull request: #88

**Comment by adeneys** [comment]
Fixed in release 2.4
